### ISSUE TITLE
Request: Ability to override only main menu button textures

### ISSUE THREAD

**Issue by BBoldt** [lumien231/Custom-Main-Menu#10]
Currently my method for doing this is editing widgets.png and loading it with resource loader. 

Problem with this is it also changes the gui buttons throughout the pack, and I'm not a fan of doing that, they just end up looking weird to me.

Are there any other alternative solutions that I haven't thought of that are possible currently?

Here are what my buttons look like right now, with custom textures:
![](http://i.imgur.com/fCOILzT.jpg)

**Comment by lumien231** [comment]
Well yes :P, you can specify custom textures for buttons.

**Comment by BBoldt** [comment]
Oh, looks like I missed that in the documentation.

I see it now. 

shhhhhhhhhhhhhhhhhhhhhhh
