### ISSUE TITLE
StringReplacer in URL

### ISSUE THREAD

**Issue by DRedDogPE** [lumien231/Custom-Main-Menu#100]
Could you add this please? if you could add this then i would be able to send a request to my php script and return data. Example: Send a request to http://somewebsite.com/?user=#username# and get details about the player such as rank on a server (using the website) that would then be able to be used as a text string.

I think this would work

**Comment by lumien231** [comment]
This already is in the 1.8.9/(1.9) version and i **really** don't want to make another 1.7.10 update. Wait till the community moves to 1.9 and then you can use it^^.

**Comment by DRedDogPE** [comment]
I made an edited version (after many hours) and got it to work.

**Comment by DRedDogPE** [comment]
Also I think there are some memory leaks with your mod but I'm not sure, it seems to use more ram than it should and slows the game down loads. (I've only noticed it when CustomMainMenu is installed but it could be another mod)

**Comment by digimbyte** [comment]
actually I would upgrade if i could, but some developers refuse to update, and other refuse to be backwards compatible. 
@DRedDogPE could you update the latest 1.7.10 with that URL string parser for me? it would mean alot.

**Comment by DRedDogPE** [comment]
[CustomMainMenu-edited.zip](https://github.com/lumien231/Custom-Main-Menu/files/345128/CustomMainMenu-edited.zip)
@digimbyte

**Comment by lumien231** [comment]
Send him a message, don't post it.
