### ISSUE TITLE
Black and pink screen [1.8.9] [Forge RC] [MultiMC]

### ISSUE THREAD

**Issue by CarboNUK** [lumien231/Custom-Main-Menu#104]
Have this problem just thought id post it just in case there is a easy fix.
Thanks,

- CarboN

![image](https://cloud.githubusercontent.com/assets/18377397/14409642/00bc03a2-ff11-11e5-8179-d813ebd1ce3c.png)

**Comment by lumien231** [comment]
Well clearly the resources aren't loaded. Do you have Resource Loader installed & the resources in the proper directory?

**Comment by CarboNUK** [comment]
![image](https://cloud.githubusercontent.com/assets/18377397/14409701/03dcc952-ff13-11e5-8195-9982d951d93a.png)

![image](https://cloud.githubusercontent.com/assets/18377397/14409702/0a894064-ff13-11e5-8f00-fd9adb2b5b20.png)

**Comment by CarboNUK** [comment]
Iit works when I delete the mainmenu.json and i get the refresh button but as soon as i drag the one to load the custom files in it does this

**Comment by CarboNUK** [comment]
![image](https://cloud.githubusercontent.com/assets/18377397/14409724/893a09e8-ff13-11e5-9504-7642a992d10c.png)

These are the only mods i have enabled rn

**Comment by lumien231** [comment]
You don't have Resource Loader installed :P

**Comment by CarboNUK** [comment]
Is that a mod?

**Comment by CarboNUK** [comment]
I installed the mod and it was 1.7.10 and it crashed my game

**Comment by lumien231** [comment]
There are versions for 1.7.10/1.8/1.8.9/1.9
