### ISSUE TITLE
A option to have menus with a custom button to link

### ISSUE THREAD

**Issue by crunkazcanbe** [lumien231/Custom-Main-Menu#11]
A option to make custom menus would be nice . Like a button you click then takes you to a blank menu you can add more buttons to . Something like modpacktweaks and launchGUI , but those only display a menu on launch . Also Could you add in a option to not create a map or even play Minecraft without a certain mod installed ?

What i am looking for is people that download my modpack have the ability to click on a button on the main menu and be brought to another menu like the main menu screen but blank and the ability to add a custom background , and custom buttons, titles , ect . This would be so I could on this new custom menu called recommended mods to install all with a custom button when clicked brings you to a web site for downloading the mod that I was not allowed to include in my mod pack .

I know you could just add this all to the main menu , but all that would do is clog up the main menu with clutter . A nice new clean menu brought up would be extremely nice . More space is a plus in my book .

Thanx -Crunk

**Comment by lumien231** [comment]
Yeah, i'm working on that .Since i build the mod purely to change the main menu and not create new menus (dummy) i have to change some stuff before that can happen. Will be in one of the near versions though (Maybe not the next one).

**Comment by crunkazcanbe** [comment]
Thanks man for calling me a dummy . I appreciate it a lot . Have a good day .

**Comment by lumien231** [comment]
Except that dummy was directed at myself but ok :P.

**Comment by Yulife** [comment]
Lumien, don't worry, some people just do not have humour ;)

**Comment by crunkazcanbe** [comment]
Sorry man for assuming the worse . I was just having a bad day myself. Sorry man , loving your mod , and can wait for that feature .

**Comment by infernocombustion** [comment]
so, this idea is basically to make a gui to customize the main menu instead of coding everything in? if so, then that would be a great improvement.

**Comment by lumien231** [comment]
No, this idea refers to not just editing the main menu but being able to create completely new gui screens.

**Comment by lumien231** [comment]
Ok got this finally finished now, will be in the next version.
