### ISSUE TITLE
black/blank screen while using slide show

### ISSUE THREAD

**Issue by kyran-b** [lumien231/Custom-Main-Menu#112]
hey there  

I've been trying to make a slide show with your wonderful mod but all i get is a blank screen. I'm unsure of what to do as there is no solution on how to fix this.

It would be nice if you can reply  XD

**Comment by FloppyDi** [comment]
Show your config

**Comment by kyran-b** [comment]
Hey there,

Sorry for waisting your time, I just copied someone else's configuration and altered theirs
