### ISSUE TITLE
Making Sub-Menus

### ISSUE THREAD

**Issue by ehamawy** [lumien231/Custom-Main-Menu#114]
How would I go about creating sub-menus? I know it has something to do with the openGui tag, but I can't seem to find any documentation about it. Any help would be great! :3

-ehamawy

**Comment by lumien231** [comment]
http://minecraft.curseforge.com/projects/custom-main-menu/pages/custom-main-menu/custom-guis

**Comment by ehamawy** [comment]
Thanks! I love ur mods btw :3

**Comment by lumien231** [comment]
Thank you! :D
