### ISSUE TITLE
Videos for background?

### ISSUE THREAD

**Issue by drudigger** [lumien231/Custom-Main-Menu#115]
Is there a way to add a video file such as a .webm and set it as the background image, i don't know if this is entirely possible without making another coremod but if its already possible to pull off on 1.7.10 that would be amazing as doing a frame by frame for 60 seconds at 60 frames a second is going to be a pain, also if it could pull the audio from the file and set that as the bgm for the title screen it would be awesome.

**Comment by lumien231** [comment]
It isn't possible i'm afraid and i don't really have any plans to add something like it either.

**Comment by drudigger** [comment]
Thanks for the reply , yea didn't think it was something that would be easily possible, if you do ever work on something like this in the future, i cant wait to see how you pull it off. Thank you so much for taking your time to answer as i know how much you must get asked things that seem near ridiculous.
