### ISSUE TITLE
the LiteLoader menu doesn't display

### ISSUE THREAD

**Issue by Hypsellis** [lumien231/Custom-Main-Menu#117]
The LiteLoader Menu on the right side of the Minecraft menu doesn't display more when Custom Main Menu is installed. So the result is that we can't access more to the parameters of LiteLoader.

**Comment by Wolf68k** [comment]
#21

**Comment by lumien231** [comment]
Thanks for reminding me :P. Fixed in 2.0.1.

**Comment by Wolf68k** [comment]
Is there any chance you can fix for the MC1.7.10 version as well?

**Comment by lumien231** [comment]
Sorry but i won't make another update for the 1.7.10 version (Especially for something this small), you can just access the lite loader panel through the options menu anyway.

**Comment by Wolf68k** [comment]
OK well it was worth a shot. Thanks anyway.
