### ISSUE TITLE
World Button

### ISSUE THREAD

**Issue by gamer88GG** [lumien231/Custom-Main-Menu#118]
I Don't know how to make a button that goes straight to a world.

I looked at the wiki page for it but I couldn't figure it out.

Can I a example config?

P.S Also its for a recreation of the Xbox Minecraft Menu.

**Comment by 23Link89** [comment]
I don't think that's possible with the mod in it's current state, however you can request to make this a feature.

**Comment by lumien231** [comment]
Post the json file you tried it with please.

**Comment by gamer88GG** [comment]
Never Mind.

**Comment by gamer88GG** [comment]
But Thanks.

**Comment by lumien231** [comment]
Ehh ok?
