### ISSUE TITLE
Cannot get link working

### ISSUE THREAD

**Issue by CrinkleCraft** [lumien231/Custom-Main-Menu#12]
I am trying to make a custom button with a link to my youtube channel. But the link will not work. As far as I can tell, the code is correct. I am using google chrome as default. The button in question is below.

		"youtube":
        {
            "text" : "CrinkleCraft Youtube Channel",
            "posX" : -100,
            "posY" : 144,
            "width" : 200,
            "height" : 20,
			"hoverText" : "youtube.com/user/acrinklecraft",
            "action" :
            {
                "type" : "openLink",
                "link" : "https://www.youtube.com/user/acrinklecraft"
            }
        },

**Comment by lumien231** [comment]
And you use version 1.1?

**Comment by CrinkleCraft** [comment]
Oh I think im using release version 1.0 for 1.7.10. I dont normally go with beta releases but I will now

**Comment by lumien231** [comment]
The "action" thing was added in 1.1, if you don't wanna use it look at older examples. (1.1 works perfectly fine though).
