### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by cauliflower69** [lumien231/Custom-Main-Menu#120]
Can you please specify that it is a client side mod so the server doesn't crash if its added. I believe 194 has this feature built in.

**Comment by lumien231** [comment]
This is in the 1.9.4 version and i won't make updates for the older versions.

**Comment by cauliflower69** [comment]
Odd, I made this post after it crashed with a FTB Unstable server (1.9.4)

**Comment by lumien231** [comment]
I just tried it myself, are you sure it was crashing because of cmm loading client stuff?

**Comment by cauliflower69** [comment]
I just double checked and http://pastebin.com/zH0DCWn9

With resource loader and cmm disabled it works fine.

**Comment by lumien231** [comment]
That's Resource Loader not CMM >.>, and there already is a 1.9.4 version of Resource Loader that's marked as a client side mod.

**Comment by cauliflower69** [comment]
Oh that's perfect then, thanks
