### ISSUE TITLE
[1.10.2] Game crashes pressing ESC with liteloader installed

### ISSUE THREAD

**Issue by tgstyle** [lumien231/Custom-Main-Menu#122]
When in game, pressing ESC causes the game to crash and hang.

Using latest version 2.0.1 of CMM and latest version of liteloader for 1.10.2

**Comment by WolfLeader116** [comment]
Yes, there's no errors, nothing. The game just stops responding. I have the FTB Unstable pack with the latest version of liteloader installed.

**Comment by autaut03** [comment]
Same

**Comment by lumien231** [comment]
Yeah, i can reproduce it but it's kinda hard to debug because the game just stops.

**Comment by iPencil** [comment]
Just saying, it has to be something you changed in the 2.0.1 version because the regular 2.0 version works fine with the latest liteloader for 1.10.2.

2.0.1 I'm getting the crash/freeze when pressing ESC. 2.0 version it's working fine. Haven't noticed anything NOT working for the 2.0 version on 1.10.2 yet either.

**Comment by lumien231** [comment]
I did add a lite loader compability patch in that version so it makes sense that it broke there, i just don't know HOW it broke pressing escape while ingame :P.

**Comment by iPencil** [comment]
What kind of compatibility patch are we talking about? Liteloader mods and the little liteloader menu are working fine on the 2.0 version :P

**Comment by lumien231** [comment]
Pretty sure the panel isn't working in the main menu on earlier versions.

**Comment by iPencil** [comment]
Uh yes you would be correct :D Not on the main menu, but everywhere else :P Not a problem for me (I prefer it haha) but I see the issue :P

**Comment by lumien231** [comment]
To be honest i myself thought that you might as well just access it in the options menu, but people asked for it so i added it. Will probably just remove the patch.

**Comment by iPencil** [comment]
Makes sense, better than some random crash that might or might not be fixed. I don't use enough liteloader mods to say for sure that it's needed in the main menu :P

**Comment by lumien231** [comment]
"Fixed" in 2.0.2
