### ISSUE TITLE
[1.7.10] Bug on code

### ISSUE THREAD

**Issue by GabrielGamer66** [lumien231/Custom-Main-Menu#127]
`[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at lumien.custommainmenu.configuration.GuiConfig.loadButtons(GuiConfig.java:297)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at lumien.custommainmenu.configuration.GuiConfig.load(GuiConfig.java:102)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at lumien.custommainmenu.configuration.ConfigurationLoader.load(ConfigurationLoader.java:144)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at lumien.custommainmenu.CustomMainMenu.reload(CustomMainMenu.java:93)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at lumien.custommainmenu.gui.GuiCustom.func_73876_c(GuiCustom.java:637)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/ERROR] [CustomMainMenu]: Error while loading new config file, trying to keep the old one loaded.
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at lumien.custommainmenu.configuration.GuiConfig.loadButtons(GuiConfig.java:297)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at lumien.custommainmenu.configuration.GuiConfig.load(GuiConfig.java:102)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at lumien.custommainmenu.configuration.ConfigurationLoader.load(ConfigurationLoader.java:144)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at lumien.custommainmenu.CustomMainMenu.reload(CustomMainMenu.java:93)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at lumien.custommainmenu.gui.GuiCustom.func_73876_c(GuiCustom.java:637)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/ERROR] [CustomMainMenu]: Error while loading new config file, trying to keep the old one loaded.
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at lumien.custommainmenu.configuration.GuiConfig.loadButtons(GuiConfig.java:297)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at lumien.custommainmenu.configuration.GuiConfig.load(GuiConfig.java:102)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at lumien.custommainmenu.configuration.ConfigurationLoader.load(ConfigurationLoader.java:144)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at lumien.custommainmenu.CustomMainMenu.reload(CustomMainMenu.java:93)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at lumien.custommainmenu.gui.GuiCustom.func_73876_c(GuiCustom.java:637)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[B#347] 2016/07/27 00:46:00 [INFORMA합ES]  [00:46:00] [Client thread/ERROR] [CustomMainMenu]: Error while loading new config file, trying to keep the old one loaded.
`

**Comment by lumien231** [comment]
Post your json file, it's probably invalid.

**Comment by GabrielGamer66** [comment]
`{
	"gui":
	{
		"background":
		{
			"image" : "minecraft:gui/changelog/background.fw.png",
			"posX" : 0,
			"poxY" : 0,
			"width" : 300,
            "height" : 500,
			"alignment" : "center"
		}
	}
}`

**Comment by lumien231** [comment]
You can't just leave whole sections like "buttons" out of the json file, make them empty if you don't want any of them.
