### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MiamiCenterPL** [lumien231/Custom-Main-Menu#128]
Crash report: http://pastebin.com/1YRvqAb7
Config: http://pastebin.com/WHBVcWuf

**Comment by lumien231** [comment]
Minecraft only accepts png textures.

**Comment by MiamiCenterPL** [comment]
Hello, I have Windows 10 and Java 8, you told me, Minecraft accepts only .png textures, not in my computer, I have .jpg and everything is fine, when I switch to .png I have Missing Texture. I repaired my error, There's my config: http://pastebin.com/v3eL6mRG , but, I have another issue, when minecraft is windowed I have this: http://scr.hu/35bn/s67oi, when Maximalized: http://scr.hu/35bn/4rbar , How do I can fix it?

**Comment by lumien231** [comment]
Presumably you want the buttons to stay on the left side of the screen, change the alignment of them to "left_center" and they will be attached to the middle left side of the window.
