### ISSUE TITLE
Text alignments

### ISSUE THREAD

**Issue by tenten8401** [lumien231/Custom-Main-Menu#131]
We need to be able to have text alignments. Not aligning from sides of screens, but proper anchors for the text instead of forced left alignment.

**Comment by lumien231** [comment]
But the text doesn't change after it has been set so you can just position it how you would like it yourself can't you?

**Comment by tenten8401** [comment]
Say I'm using something like a username, which is dynamic. I'd like to be able to align that so it's not off for players with longer or shorter usernames.

**Comment by lumien231** [comment]
Added in 2.0.4
