### ISSUE TITLE
Question: Where are your button' pictures from?

### ISSUE THREAD

**Issue by 5igm** [lumien231/Custom-Main-Menu#132]
I like one of your example very much. I want to change it to my own gui based on it. Could you tell where are your botton's pictures from? They are so cool! Thank you very much.

![multi](https://cloud.githubusercontent.com/assets/11610914/17635409/c825291e-6109-11e6-9d55-780741982533.png)
![lang](https://cloud.githubusercontent.com/assets/11610914/17635411/c82bd1b0-6109-11e6-93da-c769c9f94462.png)
![mods](https://cloud.githubusercontent.com/assets/11610914/17635410/c826cf6c-6109-11e6-9e77-3676adb5e519.png)

**Comment by tenten8401** [comment]
http://martz90.deviantart.com/art/Hex-Icons-Pack-389706981
![Hex Icons Pack](http://pre15.deviantart.net/6489/th/pre/f/2013/212/f/1/hex_icons_pack_by_martz90-d6g0rtx.jpg)

**Comment by 5igm** [comment]
Thank you very much!
