### ISSUE TITLE
How do i do the Sync feature!

### ISSUE THREAD

**Issue by zarzwour** [lumien231/Custom-Main-Menu#136]
I want to sync my main menu with a custom GUI. Please help!!!

**Comment by lumien231** [comment]
What did you try?

**Comment by zarzwour** [comment]
I have not tried anything because i dont know the command or the syntax or even where to put it

**Comment by lumien231** [comment]
Did you read [this](https://minecraft.curseforge.com/projects/custom-main-menu/pages/custom-main-menu/synced) page?

**Comment by zarzwour** [comment]
Yes. am i missing something big here?

**Comment by lumien231** [comment]
You just add "sync" : true to a slideshow / panorama / splashtext and it syncs them together.

**Comment by zarzwour** [comment]
Thank you :)
