### ISSUE TITLE
Colored text issue

### ISSUE THREAD

**Issue by FlaggedBrad** [lumien231/Custom-Main-Menu#137]
![](https://i.imgur.com/kyX0OQ2.png)

**Comment by lumien231** [comment]
Save the file with ascii encoding.

**Comment by FlaggedBrad** [comment]
uh, i dont see it
![](https://i.imgur.com/rhOjkgL.png)

**Comment by FlaggedBrad** [comment]
even notepad doesnt show the option
![](https://i.imgur.com/LA4bQEu.png)

**Comment by lumien231** [comment]
Meant ANSI, it's also called Windows-1252

**Comment by FlaggedBrad** [comment]
Thanks! Got it working! 

![](https://i.imgur.com/jLxZdNg.png)

**Comment by gdude2002** [comment]
If you can, please document this or link this issue on the page about Text elements, it'd save people like me a bunch of time.
