### ISSUE TITLE
Special characters not rendering properly

### ISSUE THREAD

**Issue by jensz12** [lumien231/Custom-Main-Menu#141]
CustomMainMenu does not render UTF-8 special charaters like æøåö and so on properly, when used in splash.txt and loaded through Resource Loader. I am saving it as UTF-8

![char](https://static.jensz12.com/splashes1.PNG)

**Comment by lumien231** [comment]
Saving it in ANSI works for me. Does it fix it for you?

**Comment by jensz12** [comment]
That works. Thank you so much. You should probably add this to the Curse pages ;-)
