### ISSUE TITLE
Memory leak in Main menu

### ISSUE THREAD

**Issue by InquisitorCM** [lumien231/Custom-Main-Menu#15]
Very unpleasant bug.
In every 10 sec in main menu memory usage growing at 100 megabytes (approximate)
When it reaches the limit of the selected - java.lang.OutOfMemoryError: GC overhead limit exceeded
No matter - 1 or 2 gb allocated.

modes:
DamageIndicators
advanced-machines-59.0.2
AdvancedSolarPanel-1.7.10-3.5.1
appliedenergistics2-rv2-beta-8
Better HUD by NukeDuck [1.7.10][1.0]
BetterFonts
BigReactors-0.4.1A2
buildcraft-6.3.3
Carpenter's Blocks v3.3.4 - MC 1.7.10 
CodeChickenCore-1.7.10-1.0.4.29-universal
CoFHCore-[1.7.10]3.0.0B9-40
CustomMainMenu-MC1.7.10-1.1
ExtraCells-1.7.10-2.2.46b72
forestry_1.7.10-3.3.0.6
GraviSuite-1.7.10-2.0.3
IC2NuclearControl-2.1.2a
immibis-core-59.0.7
industrialcraft-2-2.2.658-experimental
Iron-Chests-Mod-1.7.10
mod_VoxelCam_1.3.1_mc1.7.10
mod_voxelMap_1.2.3_for_1.7.10
mod_worldeditcui_1.7.10_00_mc1.7.10
ModularPowersuits-0.11.0.176
NotEnoughItems-1.7.10-1.0.3.78-universal
Numina-0.4.0.100
OptiFine_1.7.10_HD_U_B4
ProjectRed-1.7.10
ResourceLoader-1.0
ShadersModCore-v2.3.28-mc1.7.10-f
TabbyChat-1.11.1.65
ThermalExpansion-[1.7.10]4.0.0B8-23
ThermalFoundation-[1.7.10]1.0.0RC1-13

Without CustomMainMenu - everything works fine.

**Comment by lumien231** [comment]
Could i have the full log please?
