### ISSUE TITLE
When i create the panorama It gives me an error, pink texture.

### ISSUE THREAD

**Issue by IhaveAProblemWithCurrently** [lumien231/Custom-Main-Menu#150]
"panorama":
        {
            "images" : "modpack:panorama/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}

Here is the code i used it didnt work.
Also sorry im new to git-hub.

**Comment by IhaveAProblemWithCurrently** [comment]
Okay guys update now my panorama works but it only works when i use my title but now my title has a missing texture.

**Comment by lumien231** [comment]
Could you post your json file & resources folder.

**Comment by IhaveAProblemWithCurrently** [comment]
um i would but it says
sorry we dont support this type of file.

**Comment by IhaveAProblemWithCurrently** [comment]
sorry i did not mean to close this as i said i am new to github i will recreate a another issue with my json file and resources folder.

**Comment by IhaveAProblemWithCurrently** [comment]
i do not know how to post my json file or my resources folder because when i try it says sorry git-hub does not support this type of file.

**Comment by 2veryicey** [comment]
How did you fix the panorama?
