### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jtrent238** [lumien231/Custom-Main-Menu#151]
Here is crash report;
[Here Ya Go!](https://gist.githubusercontent.com/jtrent238/e38fca5653470eeaeb087288c4b4ac72/raw/73017085e3e4a9ac99d6ed89b2bfa09171606b1c/gistfile1.txt)

**Comment by lumien231** [comment]
"com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 142 column 6"

You have an error in your json file, run it through a json checker.

**Comment by jtrent238** [comment]
Ok Thanks, its fixed now :+1: :smiley:
