### ISSUE TITLE
Gifs on Custom Main Menu

### ISSUE THREAD

**Issue by xXJamieXx** [lumien231/Custom-Main-Menu#153]
I think I saw a post on here before about being able to have gifs included in your menus and I believe it was added to the list of features for 2.0. We now have 2.0 out but there isnt, that i can find, a way to add gifs. If there is, my bad but there isnt any documentation anyway. If you could confirm that, if not already, it will be implemented and if there is an ETA for when its going to be released?

**Comment by lumien231** [comment]
I added support for animated png files, not gifs.
