### ISSUE TITLE
Button doesn't show up in the menu

### ISSUE THREAD

**Issue by The-Fireplace** [lumien231/Custom-Main-Menu#155]
I apologize for bringing up an issue about an old Minecraft version, but the following configuration, which works in the latest Minecraft versions, doesn't add the button in 1.7.10, and my users keep complaining about it. Could you tell me what needs to be changed to get this to work in 1.7.10?

_Inside "buttons":_

"accounts":
{
"text" : "",
"posX" : 104,
"posY" : 96,
"width" : 20,
"height" : 20,
"wrappedButton" : 20,
"texture" : "accswitcher:textures/gui/cmmbutton.png",
"pressSound" : "",
"tooltip" : "You are currently logged in as #username#."
}

**Comment by lumien231** [comment]
Could you post your fml client latest log?

**Comment by The-Fireplace** [comment]
I apologize, it seems to work fine when I try to reproduce the issue. I assumed because of the number of users that have had the exact same issue and that they only report having the issue on the 1.7.10 version, that it was valid. If you want to try to see what they are doing wrong, see [this issue](https://github.com/The-Fireplace/In-Game-Account-Switcher/issues/2).

**Comment by The-Fireplace** [comment]
@lumien231 Update: It turns out that the users were trying to put it in a sub-menu, not on the main menu, and that was the problem.
