### ISSUE TITLE
Custom Button Background Not Loading (1.7.10)

### ISSUE THREAD

**Issue by 2veryicey** [lumien231/Custom-Main-Menu#162]
I am trying to put together a mod pack, however, when loading the button background, it displays a missing texture...I can't provide a console log due to the launcher crashing, however, a screenshot of the code and folder hierarchy is below:
![screen shot 2016-12-17 at 3 41 38 pm](https://cloud.githubusercontent.com/assets/9706839/21289614/580abf30-c46f-11e6-98ff-c364fb899781.png)
Image ingame:
![screen shot 2016-12-17 at 3 43 05 pm](https://cloud.githubusercontent.com/assets/9706839/21289641/37637b22-c470-11e6-8895-a9712d810bda.png)

**Comment by linktlh** [comment]
I'm having the same problem but do you have resource loader?
