### ISSUE TITLE
Custom Textures not loading

### ISSUE THREAD

**Issue by linktlh** [lumien231/Custom-Main-Menu#163]
![944529fc76febcd2c7ef4e97c32a27ea](https://cloud.githubusercontent.com/assets/15271738/21468713/10297f8e-c9e8-11e6-806a-f9399e7c2a63.png)
So I've been trying to get custom textures to load for a while. now I'm sure I'm not doing anything wrong I copied resources folder and config from project ozone (and Yes I do have resource loader) and launched and that appeared.
I'm not sure why this is happening. I'll keep testing until you reply thanks for looking into it!

**Comment by linktlh** [comment]
[latest.log.txt](https://github.com/lumien231/Custom-Main-Menu/files/671945/latest.log.txt)



Heres the log

**Comment by lumien231** [comment]
Could you post your folder structure please?

**Comment by linktlh** [comment]
I'll post it when I get home

**Comment by JackShadowFirez** [comment]
I'm guessing you're on a trip or that you forgot about your issue @linktlh, especially since you last replied 5 days ago.
