### ISSUE TITLE
How To Change Mainmenu Background Music?

### ISSUE THREAD

**Issue by kenijey** [lumien231/Custom-Main-Menu#167]
couldn't find any tutorial for this. how to do it in mainmenu.json file? please help..

**Comment by DeGariless** [comment]
I know think you can change this.

**Comment by ItzNath** [comment]
You can do this with the Ambiance mod : [](https://mods.curse.com/mc-mods/minecraft/238120-ambience-music-mod) check tutorial on youtube if you need some tuts (reply again if you need help I know how the mod work)

**Comment by kenijey** [comment]
oh guys, i solved this issue with a resource pack. thanks for answer and reminder me this issue.
