### ISSUE TITLE
missin textures

### ISSUE THREAD

**Issue by ido156012** [lumien231/Custom-Main-Menu#17]
![image](https://cloud.githubusercontent.com/assets/11078054/6271697/233282aa-b86b-11e4-880f-91925e28a23f.png)

**Comment by lumien231** [comment]
Do you have Resource loader installed? Or are you using a texture pack for the textures?

**Comment by ido156012** [comment]
nvm i maked all the textures by myself and it perfect
![untitled](https://cloud.githubusercontent.com/assets/11078054/6348891/e2c646b4-bc2c-11e4-9722-7549f975835b.png)
