### ISSUE TITLE
Offset text for buttons

### ISSUE THREAD

**Issue by DeGariless** [lumien231/Custom-Main-Menu#172]
Please add the ability to make multi-line text on buttons . I used '\n' but got an odd looking character instead. Multi-line text is useful when creating a custom toooltips.

![photoshop_2017-03-09_18-06-04](https://cloud.githubusercontent.com/assets/7571304/23779115/496d4cee-04f3-11e7-83f6-64170e9124af.png)

**Comment by DeGariless** [comment]
I had to make the Reddit image 2.5x the height that it appears to achieve this result.

**Comment by lumien231** [comment]
Added in 2.0.4
