### ISSUE TITLE
[1.10.2] [MO 0.5.0] [CMM 2.0.2] Custom Main Menu/Resource Loader/Matter Overdrive Conflict

### ISSUE THREAD

**Issue by Alaberti** [lumien231/Custom-Main-Menu#174]
Please see: https://github.com/simeonradivoev/MatterOverdrive/issues/623

I have this error: http://pastebin.com/raw/Lj4VVyAm when trying to load my textures with the 1.10.2 update for Matter Overdrive. Prior to adding their mod, all textures load fine. I'm hoping bringing this issue to both of your attention can help resolve it. Thank you for your time.

Full log: https://gist.githubusercontent.com/Alaberti/33b4222c4af6d7b1b9cd13e39e4e6e59/raw/253b7f4e006295c8bed60dcb26aae8a567cb58f7/Client%2520Log%2520for%2520CMM_MO%2520issue

Config: http://pastebin.com/raw/ysLmR6Gi

**Comment by lumien231** [comment]
It looks like the Full Log doesn't contain the error you posted.

**Comment by Alaberti** [comment]
It looks like it's not posting to log, but I can see it in the client console and Latest.log, so here you go, a fresh run with the minimum mods needed to cause the issue: 

Latest.log: http://pastebin.com/raw/G0b65eKJ
FML-Client-Latest.log: http://pastebin.com/raw/AL6APYr6

Recently nailed down that the issue happens with Journeymap 5.4.6, CMM, Resource Loader, and MO 0.5.0 (libraries notwithstanding).
