### ISSUE TITLE
Slideshow problem

### ISSUE THREAD

**Issue by infernocombustion** [lumien231/Custom-Main-Menu#18]
When I try to use the slideshow function (and I know the syntax is correct because I took the slideshow portion of the slideshow example on curse) it just leaves the background black. I've changed the file names and locations many times to see if that would fix it, but it didn't. I also tried taking away all my mods, and that didn't help either.
![issue](https://cloud.githubusercontent.com/assets/11151552/6320850/46d0e4cc-baaf-11e4-939f-8e6d72c47260.PNG)

**Comment by infernocombustion** [comment]
When I try to use the slideshow function (and I know the syntax is correct because I took the slideshow portion of the slideshow example on curse) it just leaves the background black. I've changed the file names and locations many times to see if that would fix it, but it didn't. I also tried taking away all my mods, and that didn't help either.

**Comment by infernocombustion** [comment]
here's a photo of the code
![issues code](https://cloud.githubusercontent.com/assets/11151552/6320869/d568de88-baaf-11e4-8fed-46e5a33b15dd.PNG)

**Comment by lumien231** [comment]
Hmm, seems to work fine for me: https://i.imgur.com/70dtah0.png (And wow, the panorama pictures look really great as backgrounds!)

A black background generally means that it does not have anything to draw there. Could you please post your whole json file and make sure that that's the one thats actually loaded?

**Comment by infernocombustion** [comment]
{
    "images":
    {
        "title":
        {
            "image" : "custommainmenu:textures/gui/minecraft.png",
            "posX" : -137,
            "posY" : 30,
            "width" : 512,
            "height" : 512,
            "alignment" : "top_center"
        }
    },
    
    "buttons":
    {
        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX" : -100,
            "posY" : 48,
            "width" : 200,
            "height" : 20
        },
        
        "multiplayer":
        {
            "text" : "menu.multiplayer",
            "posX" : -100,
            "posY" : 72,
            "width" : 200,
            "height" : 20
        },
        
        "mods":
        {
            "text" : "fml.menu.mods",
            "posX" : -100,
            "posY" : 96,
            "width" : 200,
            "height" : 20
        },
            
        "options":
        {
            "text" : "menu.options",
            "posX" : -100,
            "posY" : 132,
            "width" : 98,
            "height" : 20
        },
        
        "quit":
        {
            "text" : "menu.quit",
            "posX" : 2,
            "posY" : 132,
            "width" : 98,
            "height" : 20
        },
        
        "language":
        {
            "text" : "",
            "posX" : -124,
            "posY" : 132,
            "width" : 20,
            "height" : 20
        },
        
        "refresh":
        {
            "text" : "",
            "posX" : -154,
            "posY" : 132,
            "width" : 20,
            "height" : 20
        }
    },
    
    "texts":
    {
        "mojang":
        {
            "text" : "",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right"
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -50,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center"
        }
     },
        "background":
        {
            "image" : "",
            "slideshow":
            {
                "images" : ["minecraft:textures/gui/title/background/panorama_0.png","minecraft:textures/gui/title/background/panorama_1.png"],
                "displayDuration" : 100,
                "fadeDuration" : 40
            }
        }
    }
}
