### ISSUE TITLE
Background Image is not Showing

### ISSUE THREAD

**Issue by InterPlay02** [lumien231/Custom-Main-Menu#187]
Hello. I'm having this problem that should not be happening.
I've placed the background image in the resource folder, called it in the script, but nothing happens. Stays that pink and black image.
Take a look:
![problemas](https://cloud.githubusercontent.com/assets/23037423/26064871/9a6082b6-3968-11e7-9417-9cd41d76d2b1.jpg)

**Comment by SirraOsiris** [comment]
make a folder in the images folder labeled "textures" then use this: "imagens:textures/background.png",

**Comment by InterPlay02** [comment]
Ok, I will try it.

**Comment by SoulWolfX** [comment]
make the .png in caps it worked for me

**Comment by ElTuttiXd** [comment]
> Ok, I will try it.

it worked?

**Comment by InterPlay02** [comment]
I don't remember. Sorry.
¯\_(ツ)_/¯
