### ISSUE TITLE
Replacing options GUI

### ISSUE THREAD

**Issue by DromHour** [lumien231/Custom-Main-Menu#188]
Hi! I need to replace options GUI. First step was try to replace it by redirect:
`public class ReplaceOptionsGui {
	@SubscribeEvent
	public void onGuiOpenEvent(GuiOpenEvent event)
	{
	if(event.gui instanceof GuiOptions){event.gui = new OptionsGui();}
	}
}
`
But OptionsGui need two arguments: previosly GuiScreen and gameSettings 
I unable to get prev Gui because of redirection(or i just curved)

To call OptionsGui with arguments i tried to replace MainMenu and InGameMenu. BUT I can't replace MainMenu because it using your Gui. In configs i found way to call options gui:

![image](https://cloud.githubusercontent.com/assets/26818130/26334719/5ee9bffc-3f91-11e7-9f87-d9d261c5a7a5.png)

How can I replace GUI binded for gui "options"? Can I just write something like that:
ru.upigame.UpiGameAdditionals.MainMenuGui

**Comment by lumien231** [comment]
You can get the "last screen" and gamesettings from Minecaft.gameSettings / Minecraft.currentScreen
