### ISSUE TITLE
Invalid display text

### ISSUE THREAD

**Issue by PixelmonPRO** [lumien231/Custom-Main-Menu#191]
Hello! I made an additional page with copyrights, but the information on the page, like any Russian characters, is not displayed correctly
<img width="1439" alt="screenshot at 10 00-39-47" src="https://user-images.githubusercontent.com/26658563/26995572-222ef5da-4d76-11e7-8f2b-bfc9d34c0f5f.png">
<img width="770" alt="screenshot at 10 00-41-46" src="https://user-images.githubusercontent.com/26658563/26995574-270bdc94-4d76-11e7-8dc0-2a9b73dfb5c5.png">
<img width="1436" alt="screenshot at 10 00-42-06" src="https://user-images.githubusercontent.com/26658563/26995577-2a074050-4d76-11e7-80a8-7886427e1bb5.png">
But on the main home page Russian characters are displayed as needed:
<img width="1439" alt="screenshot at 10 00-40-02" src="https://user-images.githubusercontent.com/26658563/26995596-4347c6c0-4d76-11e7-82ae-dbe5950614c5.png">

**Comment by PixelmonPRO** [comment]
Up, any ideas?

**Comment by PixelmonPRO** [comment]
Any ideas?

**Comment by PixelmonPRO** [comment]
@lumien231

**Comment by lumien231** [comment]
So i'm guessing the text for the buttons on the main screen isn't loaded from pastebin? Maybe try using a [file](https://minecraft.curseforge.com/projects/custom-main-menu/pages/custom-main-menu/text) instead of pastebin for the tooltip text.
