### ISSUE TITLE
"Disconnect [From Server]" button sending to wrong place

### ISSUE THREAD

**Issue by fcpwiz** [lumien231/Custom-Main-Menu#194]
Hi there,

There's an issue when clicking the "Disconnect" button while in a server, the game sends you to the Multiplayer menu instead of the main menu.

This is unexpected because the config is set up in a way that on the main menu there is a "Connect to Official Server" [button](https://gist.github.com/fcpwiz/b7dcfc445b6f152a5acbfee191396446#file-gistfile1-txt-L47-L60) which bypasses the multiplayer menu and sends the player directly to the server. This issue didn't occur on the 1.7.10 version.

Thank you.

JAR: CustomMainMenu-MC1.10.2-2.0.5.jar
Config: https://gist.github.com/fcpwiz/b7dcfc445b6f152a5acbfee191396446

**Comment by fcpwiz** [comment]
@lumien231 Do you have an idea about what's going on with this?

**Comment by lumien231** [comment]
Seems to just be a change in Vanilla, not much i can do about that.
