### ISSUE TITLE
Suggestion: Modify Version Details

### ISSUE THREAD

**Issue by Raspen0** [lumien231/Custom-Main-Menu#2]
Could it be possible to modify what version details are shown on the main menu?

With version details i mean this:
![version details](https://cloud.githubusercontent.com/assets/2059372/5564264/df92d21a-8eb3-11e4-97aa-96b43d17ead5.png)

Currently you can disable them all at once, but it would be nice to be able to disable them individually

**Comment by twizcraft** [comment]
Im using the latest version for 1.12.2 and still can figure out how to disable the version text from showing. can you give me some insight on where to look for this?
