### ISSUE TITLE
textOffsetX/Y is documented but not implemented

### ISSUE THREAD

**Issue by LemADEC** [lumien231/Custom-Main-Menu#201]
According to https://minecraft.curseforge.com/projects/custom-main-menu/pages/custom-main-menu/elements/buttons , the text from buttons can be shifted using textOffsetX/Y.
According to current version on github and CustomMainMenu-MC1.7.10-1.9.2, those parameters aren't implemented.

Any chance we can add them?

**Comment by lumien231** [comment]
They are implemented in newer versions. I don't update 1.7.10 anymore so they won't be available there :/.
