### ISSUE TITLE
cant get custom sounds to work

### ISSUE THREAD

**Issue by jadeonking** [lumien231/Custom-Main-Menu#202]
all my textures work perfectly fine but cant get sounds to work at all as far as I can tell I thought I did everything right but I guess not any help would be appreciated (I only wrote menu1 as I was simply trying to get it to work first before writing the rest in sounds.json)

![musicfiles](http://i.imgur.com/8EwKEJ7.png)

![soundsjsonlocation](http://i.imgur.com/TKvtkcm.png)

![soundsjson](http://i.imgur.com/o8WTj3W.png)

![mainmenujsonexample](http://i.imgur.com/FqD94zK.png)

**Comment by lumien231** [comment]
Check [this](https://github.com/lumien231/Custom-Main-Menu/issues/205) issue, tested it.
