### ISSUE TITLE
Minecraft keeps crashing because of  custom main menu.

### ISSUE THREAD

**Issue by Cyanide55385** [lumien231/Custom-Main-Menu#206]
I have left a link to both my crash log and my config for CCM. If you can help that would be great.
config: https://pastebin.com/AVMieqVu
crash log: https://pastebin.com/QVTNvw8J

**Comment by lumien231** [comment]
Your buttons need the text property even if it's empty.

**Comment by zarzwour** [comment]
Remove the youtube link
