### ISSUE TITLE
Textures are not loading

### ISSUE THREAD

**Issue by Cyanide55385** [lumien231/Custom-Main-Menu#207]
The textures on my main menu are not loading how ever they are not purple and black textured the background is meant to be a custom image and the button on the left is meant to have an image on it. I will leave you my config. And yes I do have resource loader.

config:https://pastebin.com/ck9FyJ54
main menu: 
![image](https://user-images.githubusercontent.com/30540108/28747740-dc6df0ee-745a-11e7-8325-518f64523610.png)

**Comment by lumien231** [comment]
Please double check with the CMM Pages on curseforge, the "image property" of buttons is called texture. You also have another "other" sub category in your "other" category which is why your background isn't working.

**Comment by Cyanide55385** [comment]
ok ill try that and get back to you :)
