### ISSUE TITLE
Textures are now checkered

### ISSUE THREAD

**Issue by Cyanide55385** [lumien231/Custom-Main-Menu#208]
I do have resource loader. where the highlighted place is there is supposed to be a button.
Here is my config: https://pastebin.com/LHaiSagn
Here is my menu:
![2017-07-30_21 11 56](https://user-images.githubusercontent.com/30540108/28762671-2d68427a-756d-11e7-9b6d-9885cb94183c.png)

**Comment by BuckTheWeasel** [comment]
any error at the log/console ?

**Comment by Cyanide55385** [comment]
@BuckTheWeasel where do I find that?

**Comment by Cyanide55385** [comment]
@lumien231 do you have an idea on what is going on?

**Comment by BuckTheWeasel** [comment]
open your Minecraft dir and copy the logs file at:
Minecraft/logs/latest.log put it on pastbin and sen the link

**Comment by Cyanide55385** [comment]
is this it @BuckTheWeasel https://pastebin.com/JSxbKjrE

**Comment by WhiteFangPvP** [comment]
I'm having the same problem
