### ISSUE TITLE
Textures don't load

### ISSUE THREAD

**Issue by WhiteFangPvP** [lumien231/Custom-Main-Menu#209]
My textures and logos and images don't load in the mod, I have the resource mod installed, I have a list of my mod list below.
![modlist2017](https://user-images.githubusercontent.com/30640265/28852056-5f3d6002-771e-11e7-8685-5c4780347142.png)
This is my config:
{
    "images":
    {
        "title":
        {
            "image" : "modpack:textures/logo.png",
            "posX" : -137,
            "posY" : 30,
            "width" : 256,
            "height" : 256,
            "alignment" : "top_center"
        }
    },
    
    "buttons":
    {
        "singleplayer":
        {
            "text" : "Play Alone",
            "posX" : -100,
            "posY" : 48,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
        
        "multiplayer":
        {
            "text" : "Play Online",
            "posX" : -100,
            "posY" : 72,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
        
        "mods":
        {
            "text" : "Addons",
            "posX" : -100,
            "posY" : 96,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },
            
        "options":
        {
            "text" : "Settings",
            "posX" : -100,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
        
        "rage":
        {
            "text" : "Rage Quit",
            "posX" : 2,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "quit"
            }
        },
        
        "language":
        {
            "text" : "",
            "posX" : -124,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        
        "refresh":
        {
            "text" : "",
            "posX" : -154,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "texts":
    {
        "mojang":
        {
            "text" : "Created by WhiteFangPvP",
            "posX" : -127,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right"
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -50,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center",
            "texts" : "Created by WhiteFangPvP"
        },
        
        "panorama":
        {
            "images" : "minecraft:textures/gui/title/background/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}

![image](https://user-images.githubusercontent.com/30640265/28852159-0da59042-771f-11e7-84ec-f2df7a69ea4a.png)

My log:

https://pastebin.com/pKCe04Q9

Thats what it looks like, help.

**Comment by WhiteFangPvP** [comment]
https://pastebin.com/pKCe04Q9

My log ^^^

**Comment by Cyanide55385** [comment]
2 things do you have resource loader installed other is if you do take the title image out of the texture folder and do it like this  "modpack:logo.png".

**Comment by WhiteFangPvP** [comment]
Have you read it?

My textures and logos and images don't load in the mod, I have the resource mod installed.

**Comment by WhiteFangPvP** [comment]
Oh my god, thanks Cyanide55385 it worked!
Thanks a ton!

**Comment by Cyanide55385** [comment]
np bro
