### ISSUE TITLE
Liteloader panel not showing up

### ISSUE THREAD

**Issue by DouweKoopmans** [lumien231/Custom-Main-Menu#21]
when this mod is installed the little liteloader panel button, normally in the top right, doesn't show up. making it impossible to open the liteloader panel from the title screen.

**Comment by XBlackLeopardX** [comment]
I don't know anything about liteloader but one thing to note is that the mod removes all "buttons" added by other mods which you can then re-add with the wrapped button option to find the id for the wrapped button option you have to look through the log and it should tell you that you need to wrap a button to make it usable and it will give you the id of the button to wrap

**Comment by lumien231** [comment]
It's not a button though, i'll just have to patch lite loader a bit to make it recognize my gui as the main menu.

**Comment by XBlackLeopardX** [comment]
I wasnt sure if it was a button thats why i stated that I don't know anything about liteloader I added the buttons part just in case it may have been relevant, thank you for correcting me though

**Comment by ZPinka** [comment]
Are there any solutions by now? Do we have to add the ID or is it compatible by now?

**Comment by lumien231** [comment]
Fixed in 2.0.1.
