### ISSUE TITLE
Can't get my image too load

### ISSUE THREAD

**Issue by ImperfMage** [lumien231/Custom-Main-Menu#210]
Like it says I cannot get my image too load. 
https://gist.github.com/ImperfMage/662cb80ec26d6988a2655036c85e5efa

and I do have Resource Loader installed 
![purple](https://user-images.githubusercontent.com/28355914/28871000-1a04706e-7748-11e7-897e-1b8125ceec4e.PNG)

my file path
![screen](https://user-images.githubusercontent.com/28355914/28871027-405a4928-7748-11e7-9e92-6bf73d9d0890.PNG)

**Comment by Cyanide55385** [comment]
can you please give me your config? Use pastebin then send the link.

**Comment by lumien231** [comment]
Try to keep all your resource locations 100% lower case.

**Comment by Cyanide55385** [comment]
you don't need the resources in your image instead rename your image to title not Title and rename Mage to mage the change "resources:Mage:Title.png" to "mage:title.png".

**Comment by Cyanide55385** [comment]
That is how i got my title to show up
