### ISSUE TITLE
Background is checkered and buttons are not showing up

### ISSUE THREAD

**Issue by Cyanide55385** [lumien231/Custom-Main-Menu#212]
I do have resource loader. where the highlighted place is there is supposed to be a button.
Here is my config: https://pastebin.com/LHaiSagn
Here is my menu:
![2017-07-30_21 11 56](https://user-images.githubusercontent.com/30540108/28942740-5157b42c-7851-11e7-967f-84fdec366bae.png)

**Comment by lumien231** [comment]
Ok but why did you create another identical issue? 

Could you upload your textures please? Did you check the example button texture? They have to have both a normal and "hovered" version in them.

**Comment by Cyanide55385** [comment]
I'm sorry for making another one but i fixed the button problem but my background is still checkered, I would appreciate it if someone helps. :D

**Comment by DarkPLayer009** [comment]
Its simple, you just need to put the image folder in the mod pack and use their way on the code, like the examples.. you just figured out yourself now :P

**Comment by Cyanide55385** [comment]
Thank you guys so much for your help!!!!!!
