### ISSUE TITLE
Can i do randomizer images?

### ISSUE THREAD

**Issue by DarkPLayer009** [lumien231/Custom-Main-Menu#213]
I just create the menu but the images just do the same order aways.. its boring that way can i just put a randomizer on that? or i can't do that now in code?

**Comment by DarkPLayer009** [comment]
"image" : "",
			"slideshow":
			{
				"images" : ["mainmenu:textures/dp/d1.jpg","mainmenu:textures/dp/d2.jpg","mainmenu:textures/dp/d3.jpg","mainmenu:textures/dp/d4.jpg","mainmenu:textures/dp/d5.jpg","mainmenu:textures/dp/d6.jpg"],
				"displayDuration" : 200,
				"fadeDuration" : 60
			}

**Comment by lumien231** [comment]
As it says on the [Slideshow](https://minecraft.curseforge.com/projects/custom-main-menu/pages/custom-main-menu/others/background/slideshow) page on curseforge the "shuffle" property will randomly mix the images on each mc run.
