### ISSUE TITLE
Crashes when I edited the json file

### ISSUE THREAD

**Issue by AhRoon** [lumien231/Custom-Main-Menu#215]
Logs File: https://pastebin.com/eQFzqHcj

Json: https://pastebin.com/ut4qbT9K

![cap 2017-08-07 20-04-45-405](https://user-images.githubusercontent.com/25527589/29024214-f7e883a4-7bab-11e7-89f2-682c6ffc309b.png)

When I edits the Json file, after launches, the client crashed.

Can you look into that what is happening?

Thanks.

P.S. Sorry for my bad english, I'm from South Korea so I'm literally bad at English Grammar. Thank you for understanding me.

**Comment by lumien231** [comment]
The Image Property for Backgrounds is called "image", not "images"

**Comment by AhRoon** [comment]
Thanks. I will fix the issues later.

2017. 8. 7. 오후 9:50에 "Lumien" <notifications@github.com>님이 작성:
