### ISSUE TITLE
Custom Images and Background not loading even the Resource Loader Installed.

### ISSUE THREAD

**Issue by AhRoon** [lumien231/Custom-Main-Menu#216]
Hello, When I applied for Custom Images and Background, It doesn't work. Can you look what happened?
P.S. I have already Resource Loader Installed.

JSON: https://pastebin.com/SE09YARM

![cap 2017-08-08 12-38-57-470](https://user-images.githubusercontent.com/25527589/29055300-ac2f1082-7c36-11e7-907e-f5c20bff97d7.png)

![2017-08-08_12 38 21](https://user-images.githubusercontent.com/25527589/29055294-a0507c74-7c36-11e7-9bb8-d69e220abe68.png)

**Comment by BuckTheWeasel** [comment]
whats inside the Background folder ? Try this on image at background 
        "background":
        {
            "image" : "gunstermc:background/Background.png",
            "mode" : "stretch"
        }

**Comment by AhRoon** [comment]
It works well. Thanks!
