### ISSUE TITLE
pressSound&hoverSound not work 1.10.2

### ISSUE THREAD

**Issue by wingsofra** [lumien231/Custom-Main-Menu#219]
"singleplayer":
        {
            "text" : "single",
			"hoverText" : "start",
			"normalTextColor" : -1,
			"hoverTextColor" : 256,
			"pressSound" : "test:textures/button.click.ogg",
			"hoverSound" : "test:textures/button.hover.ogg",
            "posX" : 10,
            "posY" : 10,
            "width" : 100,
            "height" : 20,
			"texture" : "test:textures/null.png",
			"alignment" : "top_left",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        }

I put "button.click.ogg" and "button.hover.ogg" into resources/test/textures folder,can't work.
I tried .mp3 and .wav,can't work.
What should I do?
Sorry,my English is bad.

**Comment by wingsofra** [comment]
I love this mod,by the way.

**Comment by lumien231** [comment]
You need a sounds.json file.

#205
