### ISSUE TITLE
Colors?

### ISSUE THREAD

**Issue by DaggerTM** [lumien231/Custom-Main-Menu#220]
Is there a way to change the NormalTextColor? I saw a few modpacks do it, but now sure how to get the colors.

**Comment by lumien231** [comment]
Did you look through the properties of a label in the pages?

**Comment by DaggerTM** [comment]
What does that even mean? I'm sorry I don't understand.

**Comment by lumien231** [comment]
[CurseForge Pages](https://minecraft.curseforge.com/projects/custom-main-menu/pages/custom-main-menu)

**Comment by DaggerTM** [comment]
No I didn't, is there a way to find TextColor?

**Comment by lumien231** [comment]
All properties a label (text) can have are listed on the [Label page](https://minecraft.curseforge.com/projects/custom-main-menu/pages/custom-main-menu/elements/texts)  changing color will change the text color. Use an rgb to int converter like [this](http://www.shodor.org/stella2java/rgbint.html) to get the rgb integer from your color.

**Comment by DaggerTM** [comment]
Ahh, thank you
