### ISSUE TITLE
[1.12.1] #MCVERSION# string glitched

### ISSUE THREAD

**Issue by NovaViper** [lumien231/Custom-Main-Menu#221]
The strangest thing with the #minecraftversion# string happens in 1.12.1. When I use it, it just says '1.12' instead of '1.12.1'.

**Comment by DaggerTM** [comment]
Use this "#mcversion#.1"

**Comment by NovaViper** [comment]
@DaggerTM I know that.. But it should be internally fixed, as I'm using this mod to create a menu for a mod pack that's to be used on different versions of Minecraft

_Sent from my Samsung SM-G925P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SnowShock35** [comment]
@NovaViper you're quite right it's not supposed to be just 1.12 it should be 1.12.1

pokes @lumien231 😛

**Comment by lumien231** [comment]
On which Forge Version are you? Works fine for me.

**Comment by NovaViper** [comment]
14.22.0.2462

**Comment by SnowShock35** [comment]
@lumien231 As you said there it's working in dev only. That same issue occurred before when it wasn't localising the placeholder string.

**Comment by lumien231** [comment]
Fixed in 2.0.7

**Comment by NovaViper** [comment]
Thanks for the fix!
