### ISSUE TITLE
(1.12.1) Poof! crashes.

### ISSUE THREAD

**Issue by Migmag789** [lumien231/Custom-Main-Menu#222]
Hi lumien231 ! I launch my modpack with your mod, 2/7 loading finished, but... poof! crashes. Can you fix it please ? :D 
Thank you ! :)
[crash-2017-08-28_21.31.41-client.txt](https://github.com/lumien231/Custom-Main-Menu/files/1258002/crash-2017-08-28_21.31.41-client.txt)

**Comment by lumien231** [comment]
Did you run your json file through a json checker?

**Comment by Migmag789** [comment]
Nope, just with CTM ;)

**Comment by lumien231** [comment]
What? Please follow the "Reporting Issues" Steps on the curseforge page.

**Comment by Migmag789** [comment]
Okay, thank you :D
