### ISSUE TITLE
minecraft crash or broken image

### ISSUE THREAD

**Issue by marlon99rocks** [lumien231/Custom-Main-Menu#225]
minecraft crash or broken image i tryed everything to get this mod working i dont know what going on with it plz help i tryed to edit the text file with notepad++

**Comment by marlon99rocks** [comment]
![2017-09-27_11 31 48](https://user-images.githubusercontent.com/23298994/30891594-7a81c864-a377-11e7-9c87-76268595502e.png)

**Comment by marlon99rocks** [comment]
"images":
    {
        "title":
        {
            "image" : "modpack:rick1.png",
            "posX" : -137,
            "posY" : 30,
            "width" : 512,
            "height" : 512,
            "alignment" : "top_center"
        },
        
        "edition":
        {
            "image" : "custommainmenu:textures/gui/edition.png",
            "posX" : -49,
            "posY" : 67,
            "width" : 128,
            "height" : 16,
            "alignment" : "top_center"
        }

**Comment by marlon99rocks** [comment]
dont worry i fixed it
![2017-09-27_13 40 17](https://user-images.githubusercontent.com/23298994/30894846-9e6bf13e-a389-11e7-8b34-3c07519ee0eb.png)

**Comment by Ehrenf** [comment]
how?

**Comment by ROMVoid95** [comment]
> how?

he forgot to put **textures/gui/** after `modpack:`in the first image section
