### ISSUE TITLE
Multiplayer, Option and Quit Button's not working. 

### ISSUE THREAD

**Issue by SullivanKing** [lumien231/Custom-Main-Menu#23]
These are just the button's I am currently using, however I can't get them to work. 

"buttons":
    {   
        "multiplayer":
        {
            "text": "menu.multiplayer",
            "posX": -165,
            "posY": 15,
            "width": 100,
            "height": 20,
            "alignment": "center"
        },
        
Just one of the buttons I have laid out. Not sure if its the way I have things lined up or if it's the mod itself, I don't have an error log on start up. 

Any tips?

**Comment by lumien231** [comment]
Look at the default json file.
