### ISSUE TITLE
Text disappeared

### ISSUE THREAD

**Issue by Alfatossa** [lumien231/Custom-Main-Menu#235]
I've had no issues with custom main menu so far up until my latest version for my modpack

All the textures are there and working but the text showing on the bottom are gone
I'm speaking about the mojang copyright thing also the MC version + forge things, its all gone but i can still see it in the config file. What do i do?

I have tried with a client only using cmm and resource loader and there is still no text

MC Version: 1.10.2
Forge Version: 12.18.3.2511
CMM Version: 1.10.2-2.0.5
Resource Loader Version: 1.9.4-1.5.1

here is my config
[mainmenu.json](https://pastebin.com/8at4dHqY)

**Comment by X00LA** [comment]
You havent any entries for them.

You need the following entries:

`"labels":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "hoverText" : "§6Copyright Mojang AB. Do not distribute!",
            "posX" : -210,
            "posY" : -15,
            "color" : -1,
            "alignment" : "bottom_right",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "credits"
            }
        },
        
        "fml":
        {
            "text" : "",
            "fontSize" : 0.9,
            "posX" : 40,
            "posY" : -45,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },`

**Comment by Alfatossa** [comment]
yeah i know i fixed it
