### ISSUE TITLE
Picture loading problems

### ISSUE THREAD

**Issue by B3tah3** [lumien231/Custom-Main-Menu#237]
Hi there! Im am not able to load any pictures into my custom main menu. Editing the config files work fine, just the path directories never seem to work. Here you can see my problem:
https://i.gyazo.com/ae780ebd87269c029f40e1b687549907.png
After hours of youtube and experiments i cant find an answer on my own.
Any suggestion?

**Comment by Alfatossa** [comment]
remove the resources: since CMM already check inside the resources folder

**Comment by InterPlay02** [comment]
@Alfatossa I did this way, but still not working.
I did
"resource:modpack/Title.png" - Not working
"modpack:Title.png" - Not working
"Title.png" - Not working
"modpack:backgrounds/Title.png" - Not working

I AWAYS triple checked the name of the folders to see if there was something missing, but nothing seems to be working at all.

**Comment by InterPlay02** [comment]
The only solution that I've found was to create a resource pack and to change the minecraft logo, with my logo. And then, all that was needed was to change the size of the image, position and the position of that random texts.

**Comment by InterPlay02** [comment]
Here it is:
![pasta dos mods](https://user-images.githubusercontent.com/23037423/34690615-f2b7e582-f4a0-11e7-95d8-19ed15e0c6e0.jpg)
![pasta resource](https://user-images.githubusercontent.com/23037423/34690624-fe968fb6-f4a0-11e7-99b2-29d7a51b4b0a.jpg)
![pasta background](https://user-images.githubusercontent.com/23037423/34690630-02ff8e2c-f4a1-11e7-95ab-704bbe6263f3.jpg)
![script](https://user-images.githubusercontent.com/23037423/34690635-06c39382-f4a1-11e7-965f-301d0f8ce005.jpg)
![jogo](https://user-images.githubusercontent.com/23037423/34690712-4f8beeca-f4a1-11e7-8578-8a33a03a358b.jpg)

**Comment by InterPlay02** [comment]
I hope you fix it...
@lumien231 

This mod is really cool...

**Comment by InterPlay02** [comment]
Ok... Fixed...

The problem is: You need to put all your files inside a "modpack" folder...
So, basicly, the 'resource' folder itself is useless... Don't place anything in there hoping it will work, because it will not!

**Comment by lumien231** [comment]
Did you read the Resource Loader curse page?
