### ISSUE TITLE
(Possible Addition) Different Menus

### ISSUE THREAD

**Issue by XBlackLeopardX** [lumien231/Custom-Main-Menu#24]
I was wondering if it would be possible to add the option to also edit the singleplayer and multiplayer menus? If its possible it would be nice to have the ability to change/edit those menus

**Comment by lumien231** [comment]
I mean you can already make the singleplayer button open a custom gui of yours, at the moment you just can't re create every component of the single / multiplayer menu.

**Comment by XBlackLeopardX** [comment]
I did see you added the custom gui option in the latest update unfortunately i couldn't implement it being that the wrapped buttons option is broken in the latest update

If in the future you were able to add those other options that would be amazing it would give more control over all the guis instead of just the main
