### ISSUE TITLE
Custom Splash Text Bug

### ISSUE THREAD

**Issue by Neodark7** [lumien231/Custom-Main-Menu#25]
My custom splashes.txt seems to load only after a reload of the menu and not on the startup

PS : Can you update the documentation of your mod for the new 1.2 stuff :P

**Comment by lumien231** [comment]
Yes, i also have to update the documentation for rt 1.8 though so i'm a bit busy right now :P

**Comment by Neodark7** [comment]
ok :P can you just drop some infos for creating custom gui like changelog please ? :3

**Comment by lumien231** [comment]
I explained it to somebody on the curseforge page, look through the comments.

**Comment by Neodark7** [comment]
oh nice thanks ! :)

**Comment by Neodark7** [comment]
now we need menus with scrollbars :D

**Comment by JimmyMac3** [comment]
Suggestion - Make the config for splash-text use a resource location option.
Now - "splash-text" : (Can't specify resource location)
New way - "splash-text" : "text:splashes.txt"

If used it would override all other splashs files like those found in some resource packs.

**Comment by lumien231** [comment]
? The Splash Text already has "file" which is a resource location.

**Comment by JimmyMac3** [comment]
It does? How did I miss that. DERP!

**Comment by Reddawg99** [comment]
Also having this same issue. Other than that, everything else works fine.
