### ISSUE TITLE
Crashing on launch

### ISSUE THREAD

**Issue by TobiasDeBruijn** [lumien231/Custom-Main-Menu#251]
[crash-2018-02-18_19.07.27-client.txt](https://github.com/lumien231/Custom-Main-Menu/files/1734957/crash-2018-02-18_19.07.27-client.txt)

`{
    "images":
    {
		"modpack":
		{
            "image" : "mainmenu:Fallout-World.png",
            "posX" : -305,
            "posY" : -180,
            "width" : 600,
            "height" : 150,
            "alignment" : "center"
		}
    },
    
    "buttons":
    {
        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX" : -100,
            "posY" : -25,
            "width" : 98,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:shortbutton.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },        
        "multiplayer":
        {
            "text" : "menu.multiplayer",
            "posX" : 2,
            "posY" : -25,
            "width" : 98,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:shortbutton.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
        "options":
        {
            "text" : "menu.options",
            "posX" : -100,
            "posY" : -2,
            "width" : 98,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:shortbutton.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        }, 		
        "mods":
        {
            "text" : "Mods",
            "posX" : 2,
            "posY" : -2,
            "width" : 98,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:shortbutton.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },
        "credits":
        {
            "text" : "Credits",
            "posX" : -100,
            "posY" : 21,
            "width" : 98,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:shortbutton.png",
            "action" : 
            {
				"type" : "openGui",
				"link" : "custom.credits"
            }
        },					
        "server-files":
        {
            "text" : "Server Files",
            "posX" : 2,
            "posY" : 21,
            "width" : 98,
            "height" : 20,
			"alignment" : "center",
			"tooltip": "Comming Soon!",
			"texture" : "mainmenu:shortbutton.png"
        #    "action" : 
         #   {
         #       "type" : "openLink",
		#		"link" : "*insert link"
        #    }
        },       
        "quit":
        {
            "text" : "menu.quit",
            "posX" : -100,
            "posY" : 44,
            "width" : 200,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:longbutton.png",
            "action" : 
            {
                "type" : "quit"
            }
        },			
        "language":
        {
            "text" : "",
            "posX" : 104,
            "posY" : -25,
            "width" : 20,
            "height" : 20,
			"tooltip": "Language",
			"alignment" : "center",
			"imageWidth": "40",
			"imageHeight": "40",
			"texture" : "mainmenu:lang.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        "website":
        {
            "text" : "",
            "posX" : 104,
            "posY" : -2,
            "width" : 20,
            "height" : 20,
			"alignment" : "center",
			"tooltip": "Fallout World Website",
			"texture" : "mainmenu:web.png",
			"imageWidth": "40",
			"imageHeight": "40",
            "action" : 
            {
                "type" : "openLink",
				"link" : "http://www.fallout-world.tk"
            }
        },
        "refresh":
        {
            "text" : "",
            "posX" : 0,
            "posY" : 0,
            "width" : 20,
            "height" : 20,
			"alignment" : "center",
            "texture" : "mainmenu:refresh.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "labels":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB",
            "posX" : -75,
            "posY" : -7,
			"fontSize" : .7,
            "color" : -1,
			"hoverColor" : -1,
            "alignment" : "bottom_right"
        },
		"modpack":{
			"text" : "Fallout World",
            "posX" : 3,
            "posY" : -28,
			"fontSize" : .7,
            "color" : -1,
			"hoverColor" : -1,
            "alignment" : "bottom_left"
		},
		"forge":{
			"text" : "Forge #forgeversion#",
            "posX" : 3,
            "posY" : -21,
			"fontSize" : .7,
            "color" : -1,
			"hoverColor" : -1,
            "alignment" : "bottom_left"
		},
		"modsloaded":{
			"text" : "#modsloaded# Mods Loaded",
            "posX" : 3,
            "posY" : -14,
			"fontSize" : .7,
            "color" : -1,
			"hoverColor" : -1,
            "alignment" : "bottom_left"
		},
		"modsactive":{
			"text" : "#modsactive# Mods Active",
            "posX" : 3,
            "posY" : -7,
			"fontSize" : .7,
            "color" : -1,
			"hoverColor" : -1,
            "alignment" : "bottom_left"
		},
		"author":{
			"text" : "By TheDutchMC04 & McJty",
			"posX" : 3,
			"posY" : -35,
			"fontSize" : .7,
			"hoverColor" : -1,
			"color" : -1,
			"alignment" : "bottom_left"
		}
    },
    
    "other":
    {
		"background":
		{
			"image" : "mainmenu:background.png",
			"mode" : "fill"
		}
    }
}`

`{
    "images":
    {
		"modpack":
		{
            "image" : "mainmenu:Fallout-World.png",
            "posX" : -305,
            "posY" : -180,
            "width" : 600,
            "height" : 150,
            "alignment" : "center"
		}
    },
    
    "buttons":
    {
        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX" : -100,
            "posY" : -25,
            "width" : 98,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:shortbutton.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },        
        "multiplayer":
        {
            "text" : "menu.multiplayer",
            "posX" : 2,
            "posY" : -25,
            "width" : 98,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:shortbutton.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
        "options":
        {
            "text" : "menu.options",
            "posX" : -100,
            "posY" : -2,
            "width" : 98,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:shortbutton.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        }, 		
        "mods":
        {
            "text" : "Mods",
            "posX" : 2,
            "posY" : -2,
            "width" : 98,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:shortbutton.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },
        "credits":
        {
            "text" : "Credits",
            "posX" : -100,
            "posY" : 21,
            "width" : 98,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:shortbutton.png",
            "action" : 
            {
				"type" : "openGui",
				"link" : "custom.credits"
            }
        },					
        "server-files":
        {
            "text" : "Server Files",
            "posX" : 2,
            "posY" : 21,
            "width" : 98,
            "height" : 20,
			"alignment" : "center",
			"tooltip": "Comming Soon!",
			"texture" : "mainmenu:shortbutton.png"
        #    "action" : 
         #   {
         #       "type" : "openLink",
		#		"link" : "*insert link"
        #    }
        },       
        "quit":
        {
            "text" : "menu.quit",
            "posX" : -100,
            "posY" : 44,
            "width" : 200,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:longbutton.png",
            "action" : 
            {
                "type" : "quit"
            }
        },			
        "language":
        {
            "text" : "",
            "posX" : 104,
            "posY" : -25,
            "width" : 20,
            "height" : 20,
			"tooltip": "Language",
			"alignment" : "center",
			"imageWidth": "40",
			"imageHeight": "40",
			"texture" : "mainmenu:lang.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        "website":
        {
            "text" : "",
            "posX" : 104,
            "posY" : -2,
            "width" : 20,
            "height" : 20,
			"alignment" : "center",
			"tooltip": "Fallout World Website",
			"texture" : "mainmenu:web.png",
			"imageWidth": "40",
			"imageHeight": "40",
            "action" : 
            {
                "type" : "openLink",
				"link" : "http://www.fallout-world.tk"
            }
        },
        "refresh":
        {
            "text" : "",
            "posX" : 0,
            "posY" : 0,
            "width" : 20,
            "height" : 20,
			"alignment" : "center",
            "texture" : "mainmenu:refresh.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "labels":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB",
            "posX" : -75,
            "posY" : -7,
			"fontSize" : .7,
            "color" : -1,
			"hoverColor" : -1,
            "alignment" : "bottom_right"
        },
		"modpack":{
			"text" : "Fallout World",
            "posX" : 3,
            "posY" : -28,
			"fontSize" : .7,
            "color" : -1,
			"hoverColor" : -1,
            "alignment" : "bottom_left"
		},
		"forge":{
			"text" : "Forge #forgeversion#",
            "posX" : 3,
            "posY" : -21,
			"fontSize" : .7,
            "color" : -1,
			"hoverColor" : -1,
            "alignment" : "bottom_left"
		},
		"modsloaded":{
			"text" : "#modsloaded# Mods Loaded",
            "posX" : 3,
            "posY" : -14,
			"fontSize" : .7,
            "color" : -1,
			"hoverColor" : -1,
            "alignment" : "bottom_left"
		},
		"modsactive":{
			"text" : "#modsactive# Mods Active",
            "posX" : 3,
            "posY" : -7,
			"fontSize" : .7,
            "color" : -1,
			"hoverColor" : -1,
            "alignment" : "bottom_left"
		},
		"author":{
			"text" : "Poop",
			"posX" : 3,
			"posY" : -35,
			"fontSize" : .7,
			"hoverColor" : -1,
			"color" : -1,
			"alignment" : "bottom_left"
		}
    },
    
    "other":
    {
		"background":
		{
			"image" : "mainmenu:background.png",
			"mode" : "fill"
		}
    }
}`

**Comment by lumien231** [comment]
Run your json file through an online json checker, crashing is almost always caused by invalid json.
