### ISSUE TITLE
Picture simply not shown

### ISSUE THREAD

**Issue by PoempelPinguin** [lumien231/Custom-Main-Menu#253]
I just edited my mainmenu.json to customize, but the picture is not shown. It seems the code is correct, cause when I alter it a little bit it shows the black-pink-square, but I don't get why the picture does not want to display itself...

This is my config: https://pastebin.com/LwrTMAWK

**Comment by lumien231** [comment]
That image is not 512x512 big, change it to the actual size of the image or a multiple of it.

**Comment by PoempelPinguin** [comment]
Does not change anything.

**Comment by PoempelPinguin** [comment]
After waiting overnight and reloading client this morning logo is displayed. No idea why, but size does not seem to matter now...
