### ISSUE TITLE
The third example in curse is broken

### ISSUE THREAD

**Issue by SmileycorpMC** [lumien231/Custom-Main-Menu#26]
The third .json example on the curse page is broken, the config doesn't have working buttons and when I copied the functionality I got a crash with the following error:

java.lang.RuntimeException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 25 column 5

**Comment by lumien231** [comment]
There are problably a bunch of them broken solely because they are for older versions of cmm.
They are just meant to show you how some things are done. They don't have to work.
