### ISSUE TITLE
Plain Text doesn't show in a menu?

### ISSUE THREAD

**Issue by Ronnie0982** [lumien231/Custom-Main-Menu#263]
I have a menu that i have created, but for some reason it's only the button that can be seen on that menu?
Any problems here?

https://pastebin.com/gCtpj4tq

**Comment by lumien231** [comment]
It's "labels" not "text".

**Comment by Ronnie0982** [comment]
Didn't work...

https://pastebin.com/DdyaLsmT

**Comment by lumien231** [comment]
You are missing "" around your imageWidth / imageHeight properties.

**Comment by Ronnie0982** [comment]
Still doesn't work..
(I have added extra..)

	"label" :
	{
		"changelog":
		{
		"text":"web:http://pastebin.com/raw.php?i=MmSCr6zV",
		"posX" : 2,
		"posY" : 0,
		"imageHeight" : 50,
		"imageWidth" : 50,
		"height" : 50,
		"width" : 50,
		"alignment" : "left_center"
		}
	},

**Comment by Ronnie0982** [comment]
I am not getting any errors, it doesn't read it?

**Comment by lumien231** [comment]
I didn't mean your label i meant your buttons, also please always post the whole json file you are testing with. If you don't think it's reading your json file try to remove it and see whether CMM generates a new vanilla one for you.

**Comment by Ronnie0982** [comment]
Here is the whole file:
{
    "images":
    {
	
	
	},
	"label" :
	{
		"changelog":
		{
		"text":"web:http://pastebin.com/raw.php?i=MmSCr6zV",
		"posX" : 2,
		"posY" : 0,
		"imageHeight" : 50,
		"imageWidth" : 50,
		"height" : 50,
		"width" : 50,
		"alignment" : "left_center"
		}
	},
    "buttons": 
	{
		"back":
        {
            "text" : "Back",
			"normalTextColor" : 12303291,
			"hoverTextColor" : 3125670,
			"texture" : "mainmenu:textures/bt.png",
            "posX": -150,
            "posY": 140,
            "width" : 300,
            "height" : 20,
			"imageWidth" : 300,
			"imageHeight" : 50,
			"tooltip" : "Test 2.0",
			"alignment" : "center",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "custom.mainmenu"
            }
        },
        "news1": {
            "text" : "\u00A7aWynncraft - Reborn",
			"hoverTextColor" : 3125670,
			"texture" : "mainmenu:textures/bt.png",
            "posX": -210,
            "posY": -120,
            "width" : 400,
            "height" : 20,
			"imageWidth" : 300,
			"imageHeight" : 50,
			"alignment" : "center"
        }
	},
    "other":
    {
		"background":
		{
			"image" : "reborn:textures/menu/newsbg.png",
			"mode" : "fill"
		}
    }
}

And i will try that :D

**Comment by lumien231** [comment]
"labels" not "label"

**Comment by Ronnie0982** [comment]
Okay, it works now?

	"labels" :
	{
		"changelog":
		{
		"text":"web:http://pastebin.com/raw.php?i=MmSCr6zV",
		"posX" : 2,
		"posY" : 0,
		"imageHeight" : 50,
		"imageWidth" : 50,
		"height" : 50,
		"width" : 50,
		"tooltip" : "DD",
		"alignment" : "center"
		}
	},
