### ISSUE TITLE
Unable to add Support for CMM

### ISSUE THREAD

**Issue by jredfox** [lumien231/Custom-Main-Menu#264]
hi I was making a mod that allows multiple menus. I successfully overriden yours on startup but, you call during post gui clear the buttons which is making it super difficult as your mod is really stuborn. I will allow people still to configure their cmm menu I just want them to have scrolling through multiple menus.

What I am currently able to do:
Override CMM completly and have nothing but, default menu array show up or simply have the ability to browse through your menu and then have the browsing buttons disappear 

Things you could do:
set your event priorities to only be high or low not highest or lowest buttons shouldn't be appearing that isn't yours since you don't extend GuiMainMenu. If I was to code It I would keep only one of those events preferably high since low can get overriden. You also don't extend GuiMainScreen which is what mods unless specifically adding support are looking for so I found the button clearing completely unnecessary.

let your hash map be static in config class since only one instance of your mod is ever going to run had to go through alot of reflection just to add your menu back once I overriden yours

Don't create instanceof gui fake menu ever keep one gui this is unnecessary keep your custom configed one 

Why:
because multiple menus are cool and I will be sure to add and I will be sure to add a config to disable menu browsing if people don't want it on

**Comment by lumien231** [comment]
Well i don't remember why i changed it so my menus don't extend GuiMainMenu anymore but i'm guessing there was a reason for it^^. 

> You also don't extend GuiMainScreen which is what mods unless specifically adding support are looking for so I found the button clearing completely unnecessary.

That's what GuiFakeMain is for, mods are adding their buttons into that so i can "collect" them in the LOWEST init gui event handler.

In my Event Handler there is a field called CMMEventHandler.actualGui, if you add the switching buttons there they shouldn't get removed.

Also just to understand what you are making, does your mod allow you to switch between only CMM menus or also other menus that you made?

**Comment by jredfox** [comment]
Hi thank you for responding:

My mod allows for switching between different menus and saves the current index so yours can and will have to be overridden:

What I would like you to do is:
Set your priority on your events to only be high and low:
Allow your menu to get overriden more easily and to render all buttons in your list.

I don't want to be a depeandancy on yours so could you please not remove any buttons past a certain point as a work around for mine? It allows for menus like this. It's also configurable what menus will and won't show up but, the orignal user has to code a whitelist if a menu has to be removed.
Config: https://pastebin.com/zeHshvic
Screenshot:
![2018-04-15_00 03 29](https://user-images.githubusercontent.com/9736369/38988119-a7cdb3c6-4397-11e8-93df-85162e4643d0.png)

**Comment by jredfox** [comment]
I know one main issue: You should set your gui fake menu to only extend GuiScreen and at the low or lowest override if it's equal to your class and only if. Take a look at my event class as an example. It should have the same overrides capability and you can lower your event to high. Because mods are going to check gui main menu as well unless trying to specifically override your main menu.

What you do now:
set the gui that already extends guiscreen
on lowest check if instnaceof gui main menu

**Comment by jredfox** [comment]
merging issue with latest
