### ISSUE TITLE
Using ReAuth with CMM

### ISSUE THREAD

**Issue by ResqDiver1317** [lumien231/Custom-Main-Menu#279]
I am working on building a menu for a new modpack for our community and am trying to figure out how to get a button for ReAuth to appear. I have not been able to find any documentation on this other than a mention on ReAuth's github where they said this.

"Support for CMM is added by adding an invisible button to the mainmenu to be wrapped by CMM (Button-ID 17325)"

I cannot find any documentation on how to use CMM other than the samples listed on the curseforge page and I could not find any of them that used invisible buttons or wrappers so I have no idea how to go about doing this. Any information that can be offered would be greatly appreciated!!

**Comment by lumien231** [comment]
Try adding "wrappedButton" : 17325 to a button, should make it open the ReAuth GUI.

**Comment by ResqDiver1317** [comment]
Awesome!! Thanks for the info. I saw to do the wrapper, but had zero clue how to do it. It took me a couple tries to figure out exactly how to put what you said there (I was replacing a button we don't need anymore) but it's there and working now. Now I just have to play around with positioning to get it where I want it on the menu but that's just positions so I can do that easy enough. Thanks again!!!!
