### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Xaethon** [lumien231/Custom-Main-Menu#28]
This is probably just a derp somewhere by me, but the json is valid and as far as I can tell follows the syntax of the examples on the curseforge page. Tried quite a few variations and always get a crash.

Crash report: http://pastebin.com/PfmPFzXc
JSON: http://pastebin.com/ezaCesiC 

I am using resource loader 1.0 and the files are located like this http://puu.sh/gUPln/ec22078111.png

I'd appreciate any help you could offer, although like I said its probably just something I screwed up in the json even though its valid on http://jsonlint.com/

**Comment by lumien231** [comment]
I believe you forgot a text property or something somewhere, just try to remove elements and keep reloading till the error doesn't appear anymore. Also the background property has to go INSIDE the others property or it won't work.

**Comment by flagshipninjagames** [comment]
If you are editing the JSON on textedit on mac it sometimes uses a different type of quotation mark that caused me to crash.
