### ISSUE TITLE
i cant seem to get my main manu logo to work on 1.12.2

### ISSUE THREAD

**Issue by TGCHAVOC** [lumien231/Custom-Main-Menu#289]
![minecraft 1 12 2 12_07_2018 8_33_19 pm](https://user-images.githubusercontent.com/38301473/42621832-f90eb4fc-8612-11e8-9ec6-0cf6e57b823b.png)
no matter what i do it just comes up with missing textures 
heres a copy of my json file

{
    "images":
    {
        "title":
        {
            "image" : "modpack/logo.PNG",
            "posX" : -137,
            "posY" : 30,
            "width" : 280,
            "height" : 50,
            "alignment" : "top_center"
        },

        "edition":
        {
            "image" : "custommainmenu:textures/gui/edition.png",
            "posX" : -49,
            "posY" : 67,
            "width" : 128,
            "height" : 16,
            "alignment" : "top_center"
        }
    },

    "buttons":
    {
        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX" : -100,
            "posY" : 48,
            "width" : 200,
            "height" : 20,
            "action" :
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },

        "multiplayer":
        {
            "text" : "menu.multiplayer",
            "posX" : -100,
            "posY" : 72,
            "width" : 200,
            "height" : 20,
            "action" :
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },

        "mods":
        {
            "text" : "fml.menu.mods",
            "posX" : -100,
            "posY" : 96,
            "width" : 200,
            "height" : 20,
            "action" :
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },

        "options":
        {
            "text" : "menu.options",
            "posX" : -100,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" :
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },

        "quit":
        {
            "text" : "menu.quit",
            "posX" : 2,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" :
            {
                "type" : "quit"
            }
        },

        "language":
        {
            "text" : "",
            "posX" : -124,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "action" :
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },

        "refresh":
        {
            "text" : "",
            "posX" : -154,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" :
            {
                "type" : "refresh"
            }
        }
    },

    "labels":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "hoverText" : "�nCopyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right",
            "action" :
            {
                "type" : "openGui",
                "gui" : "credits"
            }
        },

        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -40,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },

    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center",
            "texts" : "file:minecraft:texts/splashes.txt"
        },

        "panorama":
        {
            "images" : "minecraft:textures/gui/title/background/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}
I have CMM 1.12.2 and ResourceLoader-MC1.12.1-1.5.3
If anyone knows whats going on that would be great

**Comment by Dooglesmile** [comment]
Where have you saved the image file in your modpack?

I've just started making my own custom menu and put all the images I'm using into this folder structure:
modpackroot\resources\custommainmenu\textures\gui

Then I'm loading them with 
"image" : "custommainmenu:textures/gui/mylogo.png",

Also, I'm not sure if the mod is case sensitive or not, but I always keep the image filenames and text in the json file the same case.

**Comment by jredfox** [comment]
`"image" : "modpack/logo.PNG",` make sure your logo is to lower case as resource locations are to lower case and it might not be able to find it.
