### ISSUE TITLE
Read Resource Loader Page, but my textures are still showing as missing (purple/black squares) 

### ISSUE THREAD

**Issue by Kekybra** [lumien231/Custom-Main-Menu#295]
My Textures do not work here.

### **Title not showing up:**
https://cdn.discordapp.com/attachments/423954769657462787/471098721401044992/Schermafbeelding_2018-07-24_om_01.36.53.png

1st file:
https://gyazo.com/744f6986ef2c6c4e97bf6553c5b196a5

2nd file:
https://gyazo.com/5ecdf82af35fbfed46333a109d62e92c

3rd file:
https://gyazo.com/9039197dcf166eb916e457cbac36dde6

### 
{
    "images":
    {
        "title":
        {
            "image" : "kekybra:kekycraft.png",
            "posX" : -137,
            "posY" : 30,
            "width" : 512,
            "height" : 512,
            "alignment" : "top_center"
        },
        
        "edition":
        {
            "image" : "custommainmenu:textures/gui/edition.png",
            "posX" : 49,
            "posY" : 67,
            "width" : 128,
            "height" : 16,
            "alignment" : "top_center"
        }
    },
    
    "buttons":
    {
        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX" : -100,
            "posY" : 48,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
        "accounts":
        {
        "text" : "",
        "posX" : 120,
        "posY" : 132,
        "width" : 20,
        "height" : 20,
        "wrappedButton" : 20,
        "texture" : "accswitcher:textures/gui/cmmbutton.png",
        "pressSound" : "",
        "tooltip" : "You are currently logged in as #username#."
        },

        "MomentoNetwork":
        {
            "text" : "MomentoNetwork",
            "posX" : 2,
            "posY" : 72,
            "width" : 100,
            "height" : 20,
            "action" : 
            {
                "type" : "connectToServer",
                "ip" : "mc.momentonetwork.net"
            }
        },
        
        "multiplayer":
        {
            "text" : "menu.multiplayer",
            "posX" : -102,
            "posY" : 72,
            "width" : 100,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
        
        "mods":
        {
            "text" : "fml.menu.mods",
            "posX" : -100,
            "posY" : 96,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },
            
        "options":
        {
            "text" : "menu.options",
            "posX" : -100,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
        
        "quit":
        {
            "text" : "menu.quit",
            "posX" : 2,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "quit"
            }
        },
        
        "language":
        {
            "text" : "",
            "posX" : 330,
            "posY" : -100,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },

        "refresh":
        {
            "text" : "",
            "posX" : -134,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "labels":
    {
        "Time":
        {
        "text" : "#time#",
        "posX" : 3,
        "posY" : 4,
        "normalTextColor" : 1,
        "alignment" : "top_left"
        },

        "mojang":
        {
            "text" : "Made By: Kekybra",
            "hoverText" : "�nCopyright Mojang AB. Do not distribute!",
            "posX" : -94,
            "posY" : -13,
            "color" : -1,
            "alignment" : "bottom_right",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "credits"
            }
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -46,
            "color" : -1,
            "alignment" : "bottom_left"
        },

        "ActiveUser":
        {
            "text" : "You are currently logged in as #username#.",
            "posX" : 260,
            "posY" : 275,
            "color" : 16745861,
            "alignment" : "middle_center"
        }  
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : -100,
            "posY" : 40,
            "color" : -256,
            "alignment" : "top_center",
            "texts" : "file:minecraft:texts/splashes.txt"
        },
        
        "panorama":
        {
            "images" : "minecraft:textures/gui/title/background/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}

**Comment by lumien231** [comment]
Could you post a screenshot of the whole path instead of seperate like this?
Also post your log please.
