### ISSUE TITLE
Mod Conflict

### ISSUE THREAD

**Issue by KingDan27** [lumien231/Custom-Main-Menu#297]
Forge Version: Forge-14.23.4.2739

Only Mods Installed
Custom Main Menu: CustomMainMenu-MC1.12.2-2.0.8
Resource Loader: ResourceLoader-MC1.12.1-1.5.3
Chance Cubes: ChanceCubes-1.12.2-3.2.2.227

If Chance Cubes is on Version ChanceCubes-1.12.2-3.2.1.224 everything works fine on the 227 version the textures are replaced with Minecrafts unknown texture.

Not sure if issue is with them or you thought id report here.

**Comment by ChampTheLegend** [comment]
Can confirm this is an issue, having the same problem

**Comment by MeinKraft** [comment]
chance cubes has a known bug causing resource packs not to work, use previous version 224

https://github.com/Turkey2349/ChanceCubes/issues/137

**Comment by Turkey2349** [comment]
This is an issue on my end (Chance Cubes), but it would help to have a chat about your mod and how it loads in resources so that I can make a proper fix that doesn't conflict with this mod.

**Comment by Turkey2349** [comment]
This issue seems to have been resolved. Let me know if any further conflicts occur.
