### ISSUE TITLE
Suggestion: Button Hover Text

### ISSUE THREAD

**Issue by Raspen0** [lumien231/Custom-Main-Menu#3]
Could it be possible to show text when you hover over a button?

I for example made custom buttons for the main menu, but there isn't anyplace for the button text.
So if people don't know what the button means, they can hover over it.

**Comment by joserobjr** [comment]
No language key support yet :(
![image](https://cloud.githubusercontent.com/assets/3679022/24573864/492c4ebe-1660-11e7-8799-4fc235d5c892.png)
