### ISSUE TITLE
Better Scaling with gui change

### ISSUE THREAD

**Issue by Biofusionz** [lumien231/Custom-Main-Menu#30]
Not sure how easy this would be, but to make everything scale the same when the gui scale is changed. 
Large Gui size
![image](https://cloud.githubusercontent.com/assets/6354132/6916498/abe480f6-d794-11e4-9626-131a23eafd5a.png)

Normal Gui size
![image](https://cloud.githubusercontent.com/assets/6354132/6916507/c3fb417a-d794-11e4-9cc9-bddb8387fcfc.png)

Maybe making a seperate config for each gui size would fix this?

**Comment by lumien231** [comment]
So what in that picture is not scaling with the rest?

**Comment by lumien231** [comment]
Also i feel like your alignment is wrong. The buttons and the "gray line" at the bottom should have the bottom alignment, otherwise they won't stick to it when the window is resized.

**Comment by Biofusionz** [comment]
It was the alignment I was missing. All is good now. Thanks!

**Comment by lumien231** [comment]
Ok :), will leave this open for the different menus for different gui scales thingy because i think that could actually be useful.

**Comment by Hiddenisme** [comment]
Im having an issue where adding an alignment doesn't work...

        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX" : -100,
            "posY" : 48,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }

[AFTER]

        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX" : 55,
            "posY" : -35,
            "width" : 90,
            "height" : 20,
            "alignment" : "left_center"
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }

**Comment by lumien231** [comment]
And that does NOTHING or?

**Comment by Hiddenisme** [comment]
After I add the alignment line when I hit refresh It says can't load the config. I had to remove the alignment in order to get it to load the config.
![screenshot_5](https://cloud.githubusercontent.com/assets/1483674/7004890/87e1b852-dc37-11e4-8ef1-fdd9dee685c8.png)
![error](https://cloud.githubusercontent.com/assets/1483674/7004894/95593320-dc37-11e4-834c-c044aacd390a.png)

**Comment by lumien231** [comment]
Well yes :P, you are missing a comma behind the property.

**Comment by Hiddenisme** [comment]
LOL Wow Lumien I stared at this all night long.  must have been so tired I couldn't see the comma

**Comment by Biofusionz** [comment]
I don't know if this is an issue on your part or mine, but when the window isn't maximised, or people are playing on low res screens, you can't always see the whole window.
This is what it looks like for them: 
![image](https://cloud.githubusercontent.com/assets/6354132/7180611/1e48df72-e43b-11e4-850a-cfeb0ecd967d.png)

This is what it should look like:
![image](https://cloud.githubusercontent.com/assets/6354132/7180619/28b89948-e43b-11e4-9300-0af24f2b7d7e.png)

**Comment by lumien231** [comment]
I will have to look into this but really, the only thing i could try to prevent this is to allow customization of the "point" at which everything gets resized to be smaller.
