### ISSUE TITLE
[1.12.2] Main Menu Crashes Right Before Loading Into Title Screen

### ISSUE THREAD

**Issue by PulseBeat02** [lumien231/Custom-Main-Menu#307]
Right when Minecraft Forge was about to load into the normal Minecraft title screen, it crashed saying that Custom Main Menu is causing the problem. A possible reason could be a mod conflict between **Custom Main Menu and Texfix**. Here are the versions:

**Minecraft Version: 1.12.2
CMM Version: 1.12.2-2.0.8
Texfix Version: 1.12-4.0**

**Here is the crash report: https://pastebin.com/NRSWH0Nn**

What is the real problem here?

**Comment by PulseBeat02** [comment]
Anyone here

**Comment by lumien231** [comment]
So it works fine without Texfix installed?

**Comment by PulseBeat02** [comment]
No, a possibility could be Texfix conflicting with the mod.

**Comment by lumien231** [comment]
I can't reproduce this, works fine for me on forge 14.23.5.2770, TexFix 4.0 and CMM 2.0.8.
Does this happen with the default vanilla menu?

**Comment by PulseBeat02** [comment]
No, I have a custom main menu.

**Comment by lumien231** [comment]
Try to remove all your custom images one by one. The error looks like one of your image files is invalid

**Comment by PulseBeat02** [comment]
Fixed it.
