### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by TheNimbleNinja** [lumien231/Custom-Main-Menu#311]
i created a custom menu and its crashing heres the crash log: https://gist.github.com/TheNimbleNinja/c1047daf09cf36f1b07110f29836cc0c
 and here is my json:https://gist.github.com/TheNimbleNinja/eec03d4a919301ecdfef118dd9993815 
what have i done wrong?

**Comment by lumien231** [comment]
Run your json through a json formatter (like [this](https://jsonformatter.curiousconcept.com/)) before creating issues. Your whole "buttons" category is **inside** of the images one.

**Comment by elmasbv** [comment]
Close the slideshow bracket, u havent closed it
