### ISSUE TITLE
Crash on button push

### ISSUE THREAD

**Issue by MysticAura** [lumien231/Custom-Main-Menu#32]
CMM 1.3
OpenEye 0.6
Forge 1291

When I make a wrapped button for OpenEye, it shows on my main menu just fine. However, I ctd the instant I push the button with the following crash report.

crash log here:  http://pastebin.com/Pt7JN4qY
json code here: http://pastebin.com/EyU8rFjr

**Comment by lumien231** [comment]
The Open Eye button only appears when there is something to report on right?
