### ISSUE TITLE
Textures not loading

### ISSUE THREAD

**Issue by flagshipninjagames** [lumien231/Custom-Main-Menu#33]
On the Direwolf 20 1.7.10 FTB pack, when a mod is disabled, none of the textures load. They work fine when all of the mods are enabled though. I also have the issue of the textures not loading on my own pack when I copy over the cfg. Please Help :) Here is the json file:

{
    "images":
    {
		"modpack":
		{
            "image" : "mainmenu:modpack.png",
            "posX" : -125,
            "posY" : -155,
            "width" : 250,
            "height" : 150,
            "alignment" : "center"
		}
    },
    
    "buttons":
    {
        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX" : -100,
            "posY" : 0,
            "width" : 175,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:midbutton.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
        
        "multiplayer":
        {
            "text" : "menu.multiplayer",
            "posX" : -100,
            "posY" : 25,
            "width" : 175,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:midbutton.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
        
        "mods":
        {
            "text" : "Mods",
            "posX" : -100,
            "posY" : 50,
            "width" : 175,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:midbutton.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },
        "FTB Site":
        {
            "text" : "",
            "posX" : 80,
            "posY" : 25,
            "width" : 20,
            "height" : 20,
			"alignment" : "center",
			"tooltip": "Direwolf20's YouTube Channel",
			"texture" : "mainmenu:web.png",
			"imageWidth": "40",
			"imageHeight": "40",
            "action" : 
            {
                "type" : "openLink",
				"link" : "https://www.youtube.com/user/direwolf20"
            }
        },
        "support":
        {
            "text" : "Support",
            "posX" : -100,
            "posY" : 75,
            "width" : 98,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:shortbutton.png",
            "action" : 
            {
                "type" : "openLink",
				"link" : "http://support.feed-the-beast.com/"
            }
        },
        "changelog":
        {
            "text" : "Changelogs",
            "posX" : 2,
            "posY" : 75,
            "width" : 98,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:shortbutton.png",
            "action" : 
            {
                "type" : "openLink",
				"link" : "https://feedthebeast.atlassian.net/wiki/display/PML/Public+Modpack+Listings"
            }
        },
        "options":
        {
            "text" : "menu.options",
            "posX" : -100,
            "posY" : 100,
            "width" : 98,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:shortbutton.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
        
        "quit":
        {
            "text" : "menu.quit",
            "posX" : 2,
            "posY" : 100,
            "width" : 98,
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:shortbutton.png",
            "action" : 
            {
                "type" : "quit"
            }
        },
		
        "shop":
        {
            "text" : "",
            "posX" : 80,
            "posY" : 50,
			"tooltip": "Direwolf20's Shop",
            "width" : 20,
			"imageWidth": "40",
			"imageHeight": "40",
            "height" : 20,
			"alignment" : "center",
			"texture" : "mainmenu:shop.png",
            "action" : 
            {
                "type" : "openLink",
                "link" : "http://direwolf20.spreadshirt.com/"
            }
        },
		
        "language":
        {
            "text" : "",
            "posX" : 80,
            "posY" : 0,
            "width" : 20,
            "height" : 20,
			"tooltip": "Language",
			"alignment" : "center",
			"imageWidth": "40",
			"imageHeight": "40",
			"texture" : "mainmenu:lang.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        
        "refresh":
        {
            "text" : "",
            "posX" : -20,
            "posY" : 0,
            "width" : 20,
            "height" : 20,
			"alignment" : "top_right",
            "texture" : "mainmenu:refresh.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "texts":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB",
            "posX" : -108,
            "posY" : -15,
            "color" : -1,
            "alignment" : "bottom_right"
        },
		"forge":{
			"text" : "Minecraft #mcversion#",
            "posX" : 5,
            "posY" : -35,
            "color" : -1,
            "alignment" : "bottom_left"
		},
		"modsloaded":{
			"text" : "#modsloaded# Mods Loaded",
            "posX" : 5,
            "posY" : -25,
            "color" : -1,
            "alignment" : "bottom_left"
		},
		"modsactive":{
			"text" : "#modsactive# Mods Active",
            "posX" : 5,
            "posY" : -15,
            "color" : -1,
            "alignment" : "bottom_left"
		},
		"modpack":{
			"text" : "Direwolf20 1.2.1",
            "posX" : 5,
            "posY" : -45,
            "color" : -1,
            "alignment" : "bottom_left"
		}
    },
    
    "other":
    {
        "panorama":
        {
            "images" : "minecraft:textures/gui/title/background/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}

![screen shot 2015-04-07 at 19 51 59](https://cloud.githubusercontent.com/assets/11839356/7030864/9135e274-dd5f-11e4-9d4e-c6dbedb677f8.png)

**Comment by lumien231** [comment]
Do you have Resource Loader installed?

**Comment by flagshipninjagames** [comment]
No, That Fixed It, I feel so dumb now. Thanks :D

**Comment by maxsize213** [comment]
This happened with Project Ozone 2, and not only that, it doesn't allow me to join a world. I have Resource Loader by the way. I don't have pictures.
