### ISSUE TITLE
Logo and background bug

### ISSUE THREAD

**Issue by droopi29** [lumien231/Custom-Main-Menu#34]
Hello/GoodNight

I am writing to ask you how to change the logo and the image of me when I make changes because the bind her makes me a big black and purple square

ps: sorry I'm french I use google translation so it can have a fault

cordially

droopi29

**Comment by lumien231** [comment]
Do you have Resource Loader installed to add your custom textures?

Also post your json file & your folder structure please.

**Comment by droopi29** [comment]
hello 

yes i have Resource loader

**Comment by lumien231** [comment]
I need a screenshot of the problem pls.

**Comment by lumien231** [comment]
Read the Resource Loader page again, assuming your image is in resources/test/textures/becube.png the resource location woud be "test:textures/becube.png"

**Comment by droopi29** [comment]
Thank you for your help but I have another request is it possible teamspeak opens with a button and it logged in! Reponder me quickly got a server

cordially

Droopi29
