### ISSUE TITLE
[Question]Can i made elements change their size depends on window size?

### ISSUE THREAD

**Issue by tmvkrpxl0** [lumien231/Custom-Main-Menu#351]
I put big buttons on main menu, but these buttons will be overlapped if i restore down minecraft window,
this is what happens in small window(i'm foreign user)
![image](https://user-images.githubusercontent.com/41675181/59158087-0b6d3000-8af0-11e9-95c5-3a3085bcdd87.png)
this is what happens in full screen window(it should look like this)
![image](https://user-images.githubusercontent.com/41675181/59158099-43747300-8af0-11e9-9896-b54d4d059d04.png)

**Comment by xJon** [comment]
@tmvkrpxl0 Did you close this issue because it is resolved?

**Comment by tmvkrpxl0** [comment]
ah, sorry, I should've specified reason. I no longer play on 1.12 and haven't used this mod for a long time.

**Comment by xJon** [comment]
No worries! Just for reference, this is still an issue (of lack of feature) in 1.12.2.
