### ISSUE TITLE
CMM doesn`t work?

### ISSUE THREAD

**Issue by TheAnubisGod** [lumien231/Custom-Main-Menu#358]
![2019-07-12_14-31-10](https://user-images.githubusercontent.com/49990785/61125157-bb4c0980-a4b1-11e9-9652-8497f5ad86c5.png)
mainmenu.json:
`{
    "images":
    {
        "title":
        {
            "image" : "MP:PostApocalypse.png",
            "posX" : -137,
            "posY" : 30,
            "width" : 512,
            "height" : 512,
            "alignment" : "top_center"
        },
        
        "edition":
        {
            "image" : "custommainmenu:textures/gui/edition.png",
            "posX" : -49,
            "posY" : 67,
            "width" : 128,
            "height" : 16,
            "alignment" : "top_center"
        }
    },
    
    "buttons":
    {
        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX" : -100,
            "posY" : 48,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
        
        "multiplayer":
        {
            "text" : "menu.multiplayer",
            "posX" : -100,
            "posY" : 72,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
        
        "mods":
        {
            "text" : "fml.menu.mods",
            "posX" : -100,
            "posY" : 96,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },
            
        "options":
        {
            "text" : "menu.options",
            "posX" : -100,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
        
        "quit":
        {
            "text" : "menu.quit",
            "posX" : 2,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "quit"
            }
        },
        
        "language":
        {
            "text" : "",
            "posX" : -124,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        
        "refresh":
        {
            "text" : "",
            "posX" : -154,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "labels":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "hoverText" : "§nCopyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "credits"
            }
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -40,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center",
            "texts" : "file:minecraft:texts/splashes.txt"
        },
        
        "panorama":
        {
            "images" : "minecraft:textures/gui/title/background/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}`

![2019-07-12_14-33-53](https://user-images.githubusercontent.com/49990785/61125272-1bdb4680-a4b2-11e9-951d-b2e903a15488.png)

What`s wrong? (I tried to restart the game)

log fragment: 
`[14:23:31] [Client thread/WARN]: Failed to load texture: mp:postapocalypse.png
java.io.FileNotFoundException: mp:postapocalypse.png`

**Comment by True-han** [comment]
Как создатель модов я тебе говорю, что ресурс лоадер не будет читать домены ресурсов с большими буквами, так как это ограничение имеет в себе майнкрафт.

Sorry for Russian

**Comment by TheAnubisGod** [comment]
Oh, thank you very much!)

сб, 13 июл. 2019 г., 2:48 ДП Ilya Maximov <notifications@github.com>:
