### ISSUE TITLE
[Suggestion] Supply the server name when connecting to the server

### ISSUE THREAD

**Issue by comp500** [lumien231/Custom-Main-Menu#372]
The ServerData serverName seems to be set to null when clicking a button with action connectToServer. This causes some other mods to crash, as they expect a server name to be there, and use it to name folders (see https://github.com/Tropicraft/Tropicraft/blob/1.12.2/src/main/java/net/tropicraft/core/encyclopedia/TropicalBook.java#L92).

The fix for this would be one of:
- Allow the serverName to be specified in the configuration
- Supply a serverName that is the same as the server IP

**Comment by mysticdrew** [comment]
Same issue with Journeymap
Details and Solution here. 
https://github.com/TeamJM/journeymap/issues/149#issuecomment-565826418
