### ISSUE TITLE
What do I write?

### ISSUE THREAD

**Issue by zachwaffle4** [lumien231/Custom-Main-Menu#377]
What am I supposed to write to get this file:
![custombackground](https://user-images.githubusercontent.com/56054320/66010045-46261a00-e48b-11e9-92a8-768a16ac6271.png)
To be the title screen background?
I wrote 
        "panorama":
        {
            "images" : "file:///C:/Users/admir/Downloads/custombackground.png",
            "animate" : false,
            "animationSpeed" : 0,
            "blur" : false,
            "gradient" : false
        }

**Comment by TeryKay** [comment]
Remove all of those things under "images" (and replace "images" to "image"), add "mode" : "fill" under "image" and replace "panorama" to "background".
