### ISSUE TITLE
Open Source 

### ISSUE THREAD

**Issue by whatthedrunk** [lumien231/Custom-Main-Menu#381]
I noticed from your tweet that you plan to abandon this mod and I was curious if you could open source it? This is such a staple for all mod packs I would hate to see it gone.

**Comment by lumien231** [comment]
Sure. Will upload the code this weekend.

**Comment by ROMVoid95** [comment]
i cannot thank you enough for this, is this going to be under a MIT license? i was writting a new mod for this but if it is ill be so willing to help continue this.

**Comment by True-han** [comment]
> Sure. Will upload the code this weekend.

Create multiple branches for multiple minecraft versions

**Comment by lumien231** [comment]
Might be a bit borked up from my porting / rewriting attempts. The APNG library is also missing. Seems to work though.

**Comment by whatthedrunk** [comment]
@ROMVoid95 are you working on this? If not let me know and ill talk to the team to see if someone is down.

**Comment by ROMVoid95** [comment]
all im doing at the moment is setting up the ability to set global variables that can be called recursively though any custom menu file. And seeing if any methods are available to optimize screen recognition (res /w gui scaling options).
