### ISSUE TITLE
Title Image only showing missing texture image

### ISSUE THREAD

**Issue by TheSkadoosh** [lumien231/Custom-Main-Menu#384]
I've researched this thoroughly. I've updated all my file folders to not have capital letters, I've verified it's a valid json file. I have resource manager (version 1.12.2 to match my game version) installed, but nothing works.

Here is my file path:

![image](https://user-images.githubusercontent.com/44552495/68728151-babca000-0583-11ea-82e0-4e181324e1bb.png)

Here is my config (I've only updated the "title" image: 

{
    "images":
    {
        "title":
        {
            "image" : "mainmenu:textures/amalogo.png",
            "posX" : -137,
            "posY" : 30,
            "width" : 150,
            "height" : 50,
            "alignment" : "top_center"
        },
        
        "edition":
        {
            "image" : "custommainmenu:textures/gui/amalogo.png",
            "posX" : -49,
            "posY" : 67,
            "width" : 128,
            "height" : 16,
            "alignment" : "top_center"
        }
    },
    
    "buttons":
    {
        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX" : -100,
            "posY" : 48,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
        
        "multiplayer":
        {
            "text" : "menu.multiplayer",
            "posX" : -100,
            "posY" : 72,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
        
        "mods":
        {
            "text" : "fml.menu.mods",
            "posX" : -100,
            "posY" : 96,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },
            
        "options":
        {
            "text" : "menu.options",
            "posX" : -100,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
        
        "quit":
        {
            "text" : "menu.quit",
            "posX" : 2,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "quit"
            }
        },
        
        "language":
        {
            "text" : "",
            "posX" : -124,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        
        "refresh":
        {
            "text" : "",
            "posX" : -154,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "labels":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "hoverText" : "§nCopyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "credits"
            }
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -40,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center",
            "texts" : "file:minecraft:texts/splashes.txt"
        },
        
        "panorama":
        {
            "images" : "minecraft:textures/gui/title/background/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}

Screenshot of missing texture:

![image](https://user-images.githubusercontent.com/44552495/68728489-b9d83e00-0584-11ea-8930-6874015bd09f.png)

**Comment by True-han** [comment]
Do you have ResourceLoader in modpack?
Can you send logs/latest.log?

**Comment by TheSkadoosh** [comment]
Yes I have the one made by lumien231 I'm not sure what I'm doing wrong I've changed everything possible based on reading others threads on this. I'm stumped:

![image](https://user-images.githubusercontent.com/44552495/68790855-59d5ac00-0605-11ea-8d1d-ff535c39a1f4.png)

[latest.log](https://github.com/lumien231/Custom-Main-Menu/files/3842717/latest.log)

**Comment by True-han** [comment]
I guess your texture is saved in wrong format. Try to save it with another photo editor

**Comment by TheSkadoosh** [comment]
Does it have to be PNG? I used Photoshop to export it.

**Comment by ROMVoid95** [comment]
png is generally preferred, but confirm something, are you using "title" or "edition"?

**Comment by TheSkadoosh** [comment]
I was starting with title and was going to do edition next, but haven't been able to get it to work.

**Comment by True-han** [comment]
Yea, PNG. I don't know which library Minecraft texture loader uses, but stb_i have to load all formats fine

**Comment by TheSkadoosh** [comment]
sorry I reinstalled the game and mods then screen shot after I copied the config that's why it's in both.

**Comment by ROMVoid95** [comment]
as long as it points to the right folder and file, i agree with @True-han , double check your format, if in photoshop, try exporting for web for png, i've also had to rename images for the menu to show it before as well.

**Comment by True-han** [comment]
Also select RGBA 8 bit color in photo editor if you can

**Comment by TheSkadoosh** [comment]
Cool I'll give those a shot and see if maybe that's the issue. I'll update once I've exhausted all options or found resolution. Thanks!

**Comment by TheSkadoosh** [comment]
Freaking nailed it guys, I had to save for web as PNG-8 and now it works!!! You all are fookin legends!

![image](https://user-images.githubusercontent.com/44552495/68794026-6e1ca780-060b-11ea-9894-642557e4c5fc.png)

**Comment by TheSkadoosh** [comment]
Going to close this issue. Thanks again!
