### ISSUE TITLE
Randomized Panoramas

### ISSUE THREAD

**Issue by TheVisionaryOne** [lumien231/Custom-Main-Menu#385]
Not sure if this is already implemented, but it would be **awesome** if there was a way to have the mod randomly select a panorama out of a group of panoramas on startup. That way, there's a different background to the main menu every time the game starts up. :D

**Comment by TheNasbit** [comment]
> Not sure if this is already implemented, but it would be **awesome** if there was a way to have the mod randomly select a panorama out of a group of panoramas on startup. That way, there's a different background to the main menu every time the game starts up. :D

That is already possible, I do this in my own pack:

```json
"other":
    {
        "panorama" : {
            "images": [
                "mainmenu:panorama/a/bg_%c.png", 
                "mainmenu:panorama/b/bg_%c.png",
                "mainmenu:panorama/c/bg_%c.png",
                "mainmenu:panorama/d/panorama_%c.png",
                "mainmenu:panorama/e/panorama_%c.png",
            ],
            "blur": true,
            "gradient": false
        }
    }
```

**Comment by TheVisionaryOne** [comment]
I had a feeling it might be! Thanks for letting me know!
