### ISSUE TITLE
[Suggestion] Refresh keybind

### ISSUE THREAD

**Issue by AlexejheroYTB** [lumien231/Custom-Main-Menu#388]
Sometimes, while editing, you can mess up the config file.
Accidentally getting rid of the refresh button and having to restart is a pain, especially if you have 200 mods installed.
My suggestion is that there should be a keybind that defaults to `NONE` and that, when pressed, refreshes the main menu.

**Comment by lumien231** [comment]
There already is one, it's CTRL + R.

**Comment by AlexejheroYTB** [comment]
Perhaps it should be documented somewhere then :sweat_smile:

**Comment by lumien231** [comment]
[It already is](https://www.curseforge.com/minecraft/mc-mods/custom-main-menu/pages/custom-main-menu/first-steps)

**Comment by AlexejheroYTB** [comment]
Oh, I looked on the GitHub wiki.
Thanks! 😄
