### ISSUE TITLE
Have to use a lower version of forge, is it possible?

### ISSUE THREAD

**Issue by noahpulley** [lumien231/Custom-Main-Menu#389]

**Comment by ROMVoid95** [comment]
assuming your referring to the forge version for 1.12.2
afaik, it will work with any forge version for 1.12.2 (forge-14.23.0.2486 and up)

**Comment by noahpulley** [comment]
oh, thats so weird i reinstalled it to tell you the error it gives me but it works now lol thanks anyways

**Comment by noahpulley** [comment]
nevermind, didnt install correctly
