### ISSUE TITLE
Server Connect Button

### ISSUE THREAD

**Issue by checkplysgamer** [lumien231/Custom-Main-Menu#39]
A option to add a button to join server?
In a modpack I view this: (button play tekkify)
How to put a button same this (with other text) with this mod?
Is possible?

**Comment by lumien231** [comment]
Read the documentation, there is a connectToServer action.

http://minecraft.curseforge.com/mc-mods/226406-custom-main-menu/pages/custom-main-menu

**Comment by checkplysgamer** [comment]
to not oepn a new ticket Im using this.
How to get te location YX of the screen?

**Comment by lumien231** [comment]
Just look at the coordinates of the vanilla buttons and work of that.
