### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by Arrxus** [lumien231/Custom-Main-Menu#390]
I am trying to just add a Title, and I have the file but the mod is giving me a missing texture when I try to use it.

My Directory is: C:\Users\(use)\AppData\Roaming\.minecraft\resources\textures\arrcraft\gui
And my .json file is as follows:

If you could help me figure out my problem that would be great, as I have extremely basic knowledge with coding.

{
    "images":
    {
        "title":
        {
            "image":"mainmenu:textures/arrcraft.png",
            "posX" : -137,
            "posY" : 30,
            "width" : 375,
            "height" : 200,
            "alignment" : "top_center"
        }
    },
    
    "buttons":
    {
        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX" : -100,
            "posY" : 48,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
        
        "multiplayer":
        {
            "text" : "menu.multiplayer",
            "posX" : -100,
            "posY" : 72,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
        
        "mods":
        {
            "text" : "fml.menu.mods",
            "posX" : -100,
            "posY" : 96,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },
            
        "options":
        {
            "text" : "menu.options",
            "posX" : -100,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
        
        "quit":
        {
            "text" : "menu.quit",
            "posX" : 2,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "quit"
            }
        },
        
        "language":
        {
            "text" : "",
            "posX" : -124,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        
        "refresh":
        {
            "text" : "",
            "posX" : -154,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "labels":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right"
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -40,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center",
            "texts" : "file:minecraft:texts/splashes.txt"
        },
        
        "panorama":
        {
            "images" : "minecraft:textures/gui/title/background/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}

**Comment by ROMVoid95** [comment]
assuming your png's full path name is `C:\Users(use)\AppData\Roaming.minecraft\resources\textures\arrcraft\gui\arrcraft.png`
it would be
`"image":"textures:arrcraft/gui/arrcraft.png",`

For simplicity and good file structure practice you could just have your folders this way:
`C:\Users(use)\AppData\Roaming\.minecraft\resources\mainmenu\textures\arrcraft.png`
and then for image:
`"image":"mainmenu:textures\arrcraft.png",`

>Tip: the first folder inside the resources will always be the "namespace" for assets,

(the word before **:** )

**Comment by Arrxus** [comment]
I have made the path

`C:\Users(use)\AppData\Roaming\.minecraft\resources\mainmenu\textures\arrcraft.png`

And when I make the code line 
`"image":"mainmenu:textures\arrcraft.png",`
I just get a white box with nothing inside of it and I have no idea what went wrong.
Is it possible that it's my graphics card?

**Comment by ROMVoid95** [comment]
is the arrcraft.png file actually in the textures folder?

**Comment by Arrxus** [comment]
Yes it is in the textures folder.

**Comment by ROMVoid95** [comment]
without knowing anything else if your not getting a missing texture issue then my first assumption is possibly a file format issue. have a link for the picture your using?

**Comment by Arrxus** [comment]
Like a download link or?

**Comment by ROMVoid95** [comment]
yep

**Comment by Arrxus** [comment]
![ArrCraft](https://user-images.githubusercontent.com/58871964/70857514-8b1bf300-1eb5-11ea-8c68-eeb9ecb862d9.png)

**Comment by Arrxus** [comment]
i used the textcraft.net website to make it

**Comment by ROMVoid95** [comment]
![000546-12-14-19 21_12_43](https://user-images.githubusercontent.com/42848897/70857562-928fcc00-1eb6-11ea-938c-0c90062de061.jpg)
working on my end, by chance do you have ResourceLoader installed?

**Comment by Arrxus** [comment]
I do, and I am using minecraft 1.8.9 as my computer is not the best for gaming.

**Comment by ROMVoid95** [comment]
ah never used it in that version. not sure if its the same as 1.12.2. sorry bud

**Comment by Arrxus** [comment]
It's fine I found my problem: Was using the wrong version of resource loader.  Thanks for all of your hep man
