### ISSUE TITLE
[Request] Join latest server/world action

### ISSUE THREAD

**Issue by TheNasbit** [lumien231/Custom-Main-Menu#397]
Hey there,

It would be great to add an action to join the latest session. Either latest server or latest sp-world. And "disable" the button if there is no stored last server/world.

And additionally, a placeholder-string with the latest server/world name.

Currently, I am using the "connectToServer"- action, but since it is a private server, I don't want this on the menu when I set the pack to the public. So the idea came up: "why a specific server, why not the last session" - it would be really neat - since most people play mostly a single world/server inside a pack.

**Comment by TheNasbit** [comment]
@mysticdrew any way you can do this? :3
Would round up my current [Setup](https://www.curseforge.com/minecraft/mc-mods/custom-main-menu?comment=867)!

**Comment by mysticdrew** [comment]
no
