### ISSUE TITLE
HELP! NON TEXTURED THINGY

### ISSUE THREAD

**Issue by p00p00man** [lumien231/Custom-Main-Menu#413]
So, i am making a twitch modpack and I have everything installed, resource loader and cmm. I have the code like this : {
    "images":
    {
        "title":
        {
            "image" : "techcraft:main.png",
            "posX" : -137,
            "posY" : 30,
            "width" : 512,
            "height" : 512,
            "alignment" : "top_center"
        },
        
        "edition":
        {
            "image" : "custommainmenu:textures/gui/edition.png",
            "posX" : -49,
            "posY" : 67,
            "width" : 128,
            "height" : 16,
            "alignment" : "top_center"
        }
    },
    
    "buttons":
    {
        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX" : -100,
            "posY" : 48,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
        
        "multiplayer":
        {
            "text" : "menu.multiplayer",
            "posX" : -100,
            "posY" : 72,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
        
        "mods":
        {
            "text" : "fml.menu.mods",
            "posX" : -100,
            "posY" : 96,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },
            
        "options":
        {
            "text" : "menu.options",
            "posX" : -100,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
        
        "quit":
        {
            "text" : "menu.quit",
            "posX" : 2,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "quit"
            }
        },
        
        "language":
        {
            "text" : "",
            "posX" : -124,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        
        "refresh":
        {
            "text" : "",
            "posX" : -154,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "labels":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "hoverText" : "§nCopyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "credits"
            }
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -40,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center",
            "texts" : "file:minecraft:texts/splashes.txt"
        },
        
        "panorama":
        {
            "images" : "minecraft:textures/gui/title/background/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}

And My Files are like this : 

![Capture](https://user-images.githubusercontent.com/38148994/79026609-3f651780-7b3e-11ea-8038-bfff040368cb.PNG)

Also

![Capture](https://user-images.githubusercontent.com/38148994/79026662-66234e00-7b3e-11ea-9940-87045a28d3d4.PNG)

PLEASE HELP ME... thanks!

**Comment by p00p00man** [comment]
life is sad... can someone help?

**Comment by HybridDeath** [comment]
to load a new file you need a restart, cuz i don't see error here

**Comment by p00p00man** [comment]
oh ok

**Comment by p00p00man** [comment]
that makes soo much more sense

**Comment by p00p00man** [comment]
ive kinda given up on this though, ill come back to it later... for now ill close this issue

**Comment by LordDecay26** [comment]
i have the same issue
