### ISSUE TITLE
Hello from Overwolf!

### ISSUE THREAD

**Issue by GilfromOverwolf** [lumien231/Custom-Main-Menu#430]
Hey Lumien,

Sorry for spamming, thought it would be worthwhile to try here as well as through CurseForge - 
My name is Gil from the Overwolf team - 
We’ve been reaching out to active CurseForge authors following our recent announcement regarding the acquisition of Curseforge from Twitch (here, in case you missed it).

Thought it would be cool to say hi and hear abit from you as well.
If you have any feedback , questions, ideas or thoughts you’d like to share, feel free to contact me at gil.givoni@overwolf.com, or shoot me a message on Discord Gilgamesh#5476

See you!
Gil
Overwolf Team

**Comment by lumien231** [comment]
Replied on curseforge.
