### ISSUE TITLE
Changing the Loading Screen

### ISSUE THREAD

**Issue by Flaericson** [lumien231/Custom-Main-Menu#435]
This one confuses me as I have looked through other mod-packs using CMM mod that change the initial loading screen when you boot up the game. I wanna display my own logo for the pack I've created, I think I have to use the "fml" element but I don't really know how to do it. I've mimicked other packs that have changed the loading screen, I create a folder in my "resources" folder called assets/fml/textures/gui/then my logo which I called "mojang." It is a png file aswell. I don't know, maybe I'm doing something wrong, I'm just confused and would appreciate any guidance. Yes I have resource loader installed, I can even get my own panorama to boot, I just can't change the loading screen. 

Thanks

Here's my config code:

{
    "images":
    {
        "Logo":
        {
            "image" : "mainmenu:gui/textures/title.png",
            "posX" : -100,
            "posY" : -1,
            "width" : 200,
            "height" : 100,
            "alignment" : "top_center"
        },
        
        "edition":
        {
            "image" : "mainmenu:gui/textures/edition.png",
            "posX" : -60,
            "posY" : 90,
            "width" : 128,
            "height" : 16,
            "alignment" : "top_center"
        }
    },
    
    "buttons":
    {
        "Solo":
        {
            "text" : "Solo",
            "posX" : -100,
            "posY" : 48,
            "width" : 200,
            "height" : 20,
            "texture" : "mainmenu:gui/textures/button.png",
            "imageWidth" : 350,
            "imageHeight" : 75,
	    "action" :
             
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
        
        "Server Play":
        {
            "text" : "menu.multiplayer",
            "posX" : -100,
            "posY" : 72,
            "width" : 200,
            "height" : 20,
            "texture" : "mainmenu:gui/textures/button.png",
            "imageWidth" : 350,
            "imageHeight" : 75,
            "action" :
             
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
        
        "mods":
        {
            "text" : "fml.menu.mods",
            "posX" : -100,
            "posY" : 96,
            "width" : 200,
            "height" : 20,
            "texture" : "mainmenu:gui/textures/button.png",
            "imageWidth" : 350,
            "imageHeight" : 75,
            "action" :
              
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },
            
        "Options":
        {
            "text" : "Options",
            "posX" : -100,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "texture" : "mainmenu:gui/textures/button.png",
            "imageWidth" : 350,
            "imageHeight" : 100,
            "action" :
             
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
        
        "quit":
        {
            "text" : "menu.quit",
            "posX" : 2,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "texture" : "mainmenu:gui/textures/button.png",
            "imageWidth" : 350,
            "imageHeight" : 100,
            "action" : 
           
            {
                "type" : "quit"
            }
        },
        
        "language":
        {
            "text" : "",
            "posX" : -124,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        
        "refresh":
        {
            "text" : "",
            "posX" : -154,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "labels":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "hoverText" : "§nCopyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "credits"
            }
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -40,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center",
            "texts" : "file:minecraft:texts/splashes.txt"
        },
        
        "panorama":
        {
            "images" : "mainmenu:gui/textures/panorama/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}

**Comment by MalTeeez** [comment]
I've tried changing the fml logo even in the splash.properties and can after 6 hours of work say that I wasnt able to do it because either it goes full blackscreen or just decides to crash...
I did that a year ago on 1.17.10 and in the end only changed the loading animation gif, maybe u have more luck!

**Comment by Deepfried-Chips** [comment]
you need an external mod to change the loading screen
I personally use Loading Screens by bloodnbonesgaming and Blargerist
or custom loading screen by AlexIIL
custom loading screen's description hasn't been changed in a while

**Comment by Deepfried-Chips** [comment]
> you need an external mod to change the loading screen
> I personally use Loading Screens by bloodnbonesgaming and Blargerist
> or custom loading screen by AlexIIL
> custom loading screen's description hasn't been changed in a while

after some time i realized that Loading Screens by bloodnbonesgaming and Blargerist only change the loading screen for connecting to a server or loading a singleplayer world

**Comment by lumien231** [comment]
You can't change the loading screen with CMM.
