### ISSUE TITLE
Litealoder Button support?

### ISSUE THREAD

**Issue by arves100** [lumien231/Custom-Main-Menu#44]
In VoxelMenu there is a Menu called LiteMods that open the Liteloader menu
It is possible to add them into this mod?
(P.S.: Sorry for my english , i'm italian)

**Comment by DerEnderKeks** [comment]
Look at the wiki for [Buttons](http://minecraft.curseforge.com/projects/custom-main-menu/pages/custom-main-menu/elements/buttons)/[Wrapped Buttons](http://minecraft.curseforge.com/projects/custom-main-menu/pages/custom-main-menu/elements/buttons/wrapped-buttons) :D

**Comment by DerEnderKeks** [comment]
https://github.com/lumien231/Custom-Main-Menu/issues/21
