### ISSUE TITLE
Any changes made, even if reverted(via undo or otherwise) renders a config permanently broken

### ISSUE THREAD

**Issue by SuperPupperDoggo** [lumien231/Custom-Main-Menu#440]
[this config](https://pastebin.com/wGrr1Qz1) is causing [this crash](https://pastebin.com/yVtPcuLd). All I did was modify it and then undo everything. The only thing that can fix this is deleting the config and having it re-create the default config. wtf?????

**Comment by lumien231** [comment]
There is a random "is" at the end of that file, of course it doesn't work.

**Comment by SuperPupperDoggo** [comment]
huh. odd. I never closed the text editor

**Comment by SuperPupperDoggo** [comment]
the 'is' is not there [image](https://imgur.com/a/EaBVjYM)
