### ISSUE TITLE
Add Formatting Code support

### ISSUE THREAD

**Issue by arves100** [lumien231/Custom-Main-Menu#45]
A JSon option for the text to add Blod,Underline,Strikethrough,Italic and Obfuscated

**Comment by lumien231** [comment]
Do the Formatting Codes on this site not work? 

http://minecraft.gamepedia.com/Formatting_codes

**Comment by arves100** [comment]
It works but i've got a symbol after i do that.
§Hi --> ÀHi
A symbol like this

**Comment by lumien231** [comment]
Try to change your editor to save in ASCII instead of UTF and then remove that symbol.

**Comment by arves100** [comment]
Wow, fixed if i save in ANSI. Thanks for your help.
