### ISSUE TITLE
World Sync Mod Support...

### ISSUE THREAD

**Issue by elix-x** [lumien231/Custom-Main-Menu#46]
All i need is to be able to install this mod with others that add custom buttons to main menu. Like World Sync Mod... And the pain is: i can add a button, but i can't send it to gui that is not custom...

Because i'm mc modder, i'll have to get source and change some things for myself to be able to run modded guis.

I will have to deobfuscate and decompile jar and all i will try to do is to add new value of button (class.), which will parse class and instanate it...

Or i'll write transformer, to do this...

In the worst case, i'll just delete mod... (delete mod each time you update modpack with curse...)...

**Comment by lumien231** [comment]
That's exactly what wrapped buttons do?

**Comment by elix-x** [comment]
Ok, i should read more... And you should make information more easily findable...

Also, i'm not getting any log with ...wrapped button... Also, i doesn't seem to be working with world sync: it's using button id 10 (according to decomp), but if i do wrappedButton = 10, i get this:
```Initiating Wrapped Button 10 with null```
And i don't see this button in menu...

**Comment by lumien231** [comment]
Well the mod is written in scala so i'm not quite sure how he actually adds the button to the main menu but he seems to do it in a "non standard" way.

**Comment by elix-x** [comment]
I found id 10 in his button press event (Events.class)... 
I'm not sure how he adds this button either...
I'm learning scala, but normal java decompiler does not seems to decompile scala...

**Comment by lumien231** [comment]
Yeah, i see how he tests for the press which should be compatible with cmm and i assume he does the adding in his ClientTickEvent but my decompiler doesn't give me logic code for that.

**Comment by elix-x** [comment]
I know... But i don't understand which id he takes, if 10 is null... If you have no idea, i'll end up writing mini mod just for that... (printing all buttons to find needed, or adding button in good way...)...

**Comment by lumien231** [comment]
Oh he does use id 10, cmm just isn't able to detect the adding of the button.

**Comment by elix-x** [comment]
Why?

**Comment by lumien231** [comment]
Like i said, he doesn't seem to add the button in the place every other mod does it (InitGuiEvent).

**Comment by elix-x** [comment]
Ok, i see... But how he does that??? I can't seem to understand either...
Wait a minute, he has github! :) :( But not for world sync...

**Comment by elix-x** [comment]
Finally decompiled it correctly... He is adding it in clientTick event... Oh my... Why so difficult???

**Comment by elix-x** [comment]
So what do you think i have to do???
