### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by FuriousG** [lumien231/Custom-Main-Menu#472]
Nothing is loading in (images wise) here is my config:

{
    "images":
    {

        "title":
        {
            "image" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/minecraft.png",
            "posX" : -450,
            "posY" : -50,
            "width" : 720,
            "height" : 720,
            "alignment" : "right_center"
        },
        
        "edition":
        {
            "image" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/edition.png",
            "posX" : -325,
            "posY" : 5,
            "width" : 165,
            "height" : 21,
            "alignment" : "right_center"
        }
    },
    
"buttons":
    {     
		"singleplayer":
        {
            "text" : "menu.singleplayer",
			"normalTextColor" : 12303291,
			"hoverTextColor" : 3125670,
			"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
            "posX" : 97,
            "posY" : -100,
            "width" : 196,
            "height" : 30,
			imageWidth : 100,
			imageHeight : 50,
			"alignment" : "left_center",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },		

		"multiplayer":
        {
            "text" : "menu.multiplayer",			
			"normalTextColor" : 12303291,
			"hoverTextColor" : 3125670,
			"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
            "posX" : 97,
            "posY" : -65,
            "width" : 196,
            "height" : 30,
			imageWidth : 100,
			imageHeight : 50,
			"alignment" : "left_center",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
               
		"options":
        {
            "text" : "menu.options",
			"normalTextColor" : 12303291,
			"hoverTextColor" : 3125670,
			"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
            "posX" : 97,
            "posY" : -30,
            "width" : 196,
            "height" : 25,
			imageWidth : 100,
			imageHeight : 50,
			"alignment" : "left_center",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
		        
		"language":
        {
            "text" : "options.language",
			"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
            "posX" : 97,
            "posY" : 0,
            "width" : 196,
            "height" : 25,
			imageWidth : 100,
			imageHeight : 50,			
			"alignment" : "left_center",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
                    
        "quit":
        {
            "text" : "menu.quit",
			"normalTextColor" : 16729156,
			"hoverTextColor" : 14483456,
			"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
            "posX" : 97,
            "posY" : 65,
            "width" : 196,
            "height" : 25,
			imageWidth : 100,
			imageHeight : 50,
			"alignment" : "left_center",
			"hoverText" : "No! Don't leave!",
            "action" : 
            {
                "type" : "quit"
            }
        },
		
        "mods":
        {
            "text" : "Mods (#modsloaded#/#modsactive#)",
			"normalTextColor" : 6710886,
			"hoverTextColor" : 3125670,
			"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
            "posX" : 97,
            "posY" : 30,
            "width" : 196,
            "height" : 25,
			imageWidth : 100,
			imageHeight : 50,
			"alignment" : "left_center",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }

        }
    },
    
    "labels":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "hoverText" : "§nCopyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "credits"
            }
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -45,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : -118,
            "posY" : 5,
            "color" : -256,
            "alignment" : "right_center",
            "texts" : "file:minecraft:texts/splashes.txt"
        },
        
        "background":
        {
            "image" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/menubackground.png",
            "mode" : "fill"
        }
    }
}
![Screenshot 2021-04-07 021615](https://user-images.githubusercontent.com/82079549/113819421-4883c700-9747-11eb-99d9-1927dfd01ef7.png) Is what it looks like and this is what it is supposed to look like
![V2 Preview](https://user-images.githubusercontent.com/82079549/113819553-7832cf00-9747-11eb-9205-d371991d1960.png)

**Comment by FuriousG** [comment]
The top image is what it looks like for me and the bottom one is what it is supposed to look like, This is the Custom Main Menu or CMM for short

**Comment by FuriousG** [comment]
If you need any more information

**Comment by FuriousG** [comment]
Minecraft Version: 1.12.2
Forge version: 1.12.2-14.23.5.2854
CMM version: CustomMainMenu-MC1.12.2-2.0.9
RL (Resource Loader) version: ResourceLoader-MC1.12.1-1.5.3

as I stated in the title, I'm unable to load any images, only getting the "missing texture" pink-black thingy...

Edit: I was also going to put this into another mod pack that I have created and I wanted this to be separate so I wouldn't mess anything else up, Basically, I made this so then I can mess around with it and stuff then integrate it with the other one that I have so I need this to be fixed to make the other pack complete. Thanks for the Help If you help me!

**Comment by FuriousG** [comment]
So, Basically what is wrong is that there aren't any textures loading in.

**Comment by FuriousG** [comment]
Someone else helped me in a same topic issue so this is not needed any more

**Comment by felipeleite5w** [comment]
> Someone else helped me in a same topic issue so this is not needed any more

what did you do?
