### ISSUE TITLE
wrappedButton Not working. CCM 1.5 1.7.10

### ISSUE THREAD

**Issue by mindcloud69** [lumien231/Custom-Main-Menu#48]
Tried implementing a wrapped button for [Server Sync](http://minecraft.curseforge.com/mc-mods/231297-serversync) and nothing showed on the menu or in the logs. So I then tried to use one of the examples for OpenEye to no avail. 
Here is the syntax I used placed under the Buttons section.

```
    "ModpackUpdate":
    {
        "text" : "Modpack Update",
        "posX" : -100,
        "posY" : 24,
        "width" : 200,
        "height" : 20,
        "wrappedButton" : "6001"
    },
```
OpenEye example.
```
        "openeye":
        {
            "text" : "",
            "texture" : "custommainmenu:textures/gui/openeye.png",
            "posX" : 104,
            "posY" : 112,
            "width" : 20,
            "height" : 20,
            "wrappedButton" : 666
        },
```
[Client Log](https://gist.githubusercontent.com/mindcloud69/b9633bcd8c8cdf3a8ec7/raw/gistfile1.txt)
[Main Menu Screenshot](http://imgur.com/5YEHYd5)
[mainmenu.json](https://gist.github.com/mindcloud69/07b2e82708492de40dc9)

Note: also tried with cmm 1.4 and 1.3

**Comment by mindcloud69** [comment]
Lumien can I help with any more info or logs on this issue?

**Comment by lumien231** [comment]
I assume your open eye button also didn't work, the open eye button only actually appears when there was a crash last start. 

Also in the one for ServerSync, try to remove the "".

**Comment by mindcloud69** [comment]
Correct the open eye button does not show up. Remove quotes around 6001 same result. The odd thing is I did have it show up one time without a texture while my MC window was the first started to the default smaller size. But when I clicked on it it didn't do anything and it disappeared if I maximized the window or entered any sub menu. This was without any changes to any mods or config files at the time.

**Comment by mindcloud69** [comment]
This is what I meant by is some times shows up.
http://imgur.com/7gFWfEl
But next time I start the game it may not show up at all.  This is also with v1.6 
http://imgur.com/fNGVlnP
At least the open eye button seams to work in 1.6

**Comment by wackoamd1** [comment]
mindcloud did u manage to find a solution , my button isn't showing up either

**Comment by lumien231** [comment]
https://github.com/superzanti/ServerSync/issues/27
