### ISSUE TITLE
Text hover issue?

### ISSUE THREAD

**Issue by Wolf68k** [lumien231/Custom-Main-Menu#49]
I'm not sure if this is an issue or if it was meant to be like this. So please pardon me if it is as intended.

I have some text, see the code below, I have the color value set. When I happen to hover over it, it changes to white.
	"by":
        {
            "text" : "By:",
			"color" : 49087,
            "posX" : 2,
            "posY" : -15,
            "alignment" : "bottom_left"
        },
For the work around I added "hoverColor" : 49087,

Side note: I originally used color codes on the text but someone reported an issue to where they didn't show up correctly.
Sample of the original code using color code instead of color value:
	"by":
        {
            "text" : "§3By:",
            "posX" : 2,
            "posY" : -15,
            "alignment" : "bottom_left"
        },
Their resulting issue: http://i.imgur.com/CpLwjWt.jpg
I'm thinking it might be because of a different language keyboard setting or something like that.

**Comment by lumien231** [comment]
The first thing is intended yes, when hoverColor is not set it is white, not color. 

For the second thing you probably wanna try to save the json files in ASCI instead of whatever you are saving it right now. That generally fixes weird character issues with color codes.

**Comment by Wolf68k** [comment]
I'm using Notepad++ and the Encoding is set to ANSI and saved as a txt file, well json.
So do you mean to save it as ANSI or UTF-8, there is no ASCII option that I can see?

I should also point out that when I look it in-game it's fine. Even after I added to the zip with the rest of the configs, upload that to the pack site and download it from the launcher.
It's the random others that have the problem. That screen shot was from someone with that problem.

**Comment by lumien231** [comment]
Yeah i mean ANSI^^
