### ISSUE TITLE
wrappedButton Incompatibility with OpenEye

### ISSUE THREAD

**Issue by wolstech** [lumien231/Custom-Main-Menu#5]
The "wrappedButton" functions are incompatible with OpenEye's button (the eye/checkmark that appears when it sends reports or has information for you). The button appears but is blank with no picture on it and the orange flashing effect doesn't work, likely because the button is getting redrawn by CMM and can't be controlled by OpenEye.

Picture of a test UI attached. (Note the blank button over the Forge info text in lower left, that's supposed to be OpenEye's button)

![openeyecmmbug](https://cloud.githubusercontent.com/assets/10351771/5581598/e5917450-902a-11e4-9977-44cc9cc04d2d.png)

**Comment by Fogger** [comment]
I can't find any occurrence of "use a wrapped button to config this" in my logs for OpenEye. what was the id?

**Comment by wolstech** [comment]
Its in fml-client-0.log (not latest.log). For me its ID was 666.

**Comment by lumien231** [comment]
^

**Comment by Fogger** [comment]
Thanks, that ID worked for me also.

My Technic pack doesn't seem to create any fml-client-#.log's for some reason. in the logs folder is only ever a latest.log and compressed backups of what looks like older versions of latest.log, none of which have ever produced this msg.  I have been through every dir with a fine tooth comb, they are nowhere!

**Comment by Fogger** [comment]
I just switched to VannilaForge to find ID's, but now that I have the fml-client logs, none of them contain the "wrapped button" text for iChun's Tabula mod, see pic: http://i.imgur.com/uCjSW3P.png

**Comment by lumien231** [comment]
Will be probably fixed in Tabula

**Comment by wolstech** [comment]
The Technic Pack issue happened for me too, and I did the same thing...ran it in vanilla launcher to get the ID. Their launcher causes 1.7.10 packs to not generate FML logs for some reason. Perhaps file a bug report over at Technic's website about this?

As for Tabula, no comment as I don't use that mod.
