### ISSUE TITLE
Custom code

### ISSUE THREAD

**Issue by scriptcoded** [lumien231/Custom-Main-Menu#50]
Hello there!

I'm having to customise the main menu for a modpack. The main menu should have a button that clones a blank world and start it. So everytime the okayer clicks the button he would be launced into a new world. Identical each time. I managed to edit the base classes of Minecraft, but it won't compile. So I figured I could use your mod. But sadly, I cannot clone a folder to the saves folder. Would there be any way to implement this really quickly (I guess there is, since I did it almost the same way (I think)) or is there any way I could access the sourcecode of your awesome mod?

Thank you,
Malcolm

**Comment by lumien231** [comment]
So if they keep pressing the button there are going to be tons of clones or are they supposed to be deleted after the player leaves?

**Comment by scriptcoded** [comment]
Well, in my code i replaced the world each time, but i guess that'd be an option. Maybe use a .conf file? And then have a button to clear them. I dunno just brainstorming. But i simply replaced the world on load. :)

**Comment by lumien231** [comment]
You see i'm not sure whether this should go in Custom Main Menu as it really doesn't have much to do with the menu^^.

**Comment by scriptcoded** [comment]
Well, you could create a child mod. Or simply add a clone/delete/create folder action :)

**Comment by iPencil** [comment]
@scriptcoded 
This mod: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2126669-1-7-x-1-6-4-forge-lockdown

pretty much almost does what you are asking for.

**Comment by scriptcoded** [comment]
Thank you @iPencil :)
That's very helpful!
