### ISSUE TITLE
Feature request: Consistent slideshow

### ISSUE THREAD

**Issue by iPencil** [lumien231/Custom-Main-Menu#51]
With custom guis, the problem with slideshow backgrounds is that they will always reset back to the first image when you switch gui "menus".

Would it be possible to simply specify a "master" background in the main file, that will be used accross all the custom guis I make? Something like 
"copyMainBackground" : "true"
in the custom gui

So that the slideshow doesn't reset back to the first image?

**Comment by lumien231** [comment]
I would maybe just add a "global" property to slideshows, if you set it to true it's going to be linked to everyother slideshow that has global as true.

**Comment by iPencil** [comment]
Yes that would be great too :)
It doesn't really matter where you set the property :)
