### ISSUE TITLE
Glitching Texts whenever I hover over an Aura Node

### ISSUE THREAD

**Issue by gabor6505** [lumien231/Custom-Main-Menu#54]
If I hover over a Thaumcraft Aura Node, every text on the screen added by CMM, gets bright. I am not sure if this is a problem with Thaumcraft, OptiFine, or maybe WAILA, but I will test it without OptiFine and WAILA if you need it.

Screenshots:
![2015-07-24_11 32 26](https://cloud.githubusercontent.com/assets/12859334/8871730/c8f837ec-31f7-11e5-8964-28ebb3804150.png)
![2015-07-24_11 32 28](https://cloud.githubusercontent.com/assets/12859334/8871750/e684fa16-31f7-11e5-90e4-8a0ad25bee1b.png)

Minecraft Version: 1.7.10
ResourceLoader Version: 1.2
CustomMainMenu Version: 1.5

If you need more info, forge log, modlist, tell me.

**Comment by lumien231** [comment]
You are Ingame though? There is nothing from CMM visible in that Screenshot right?

**Comment by gabor6505** [comment]
Oh, I am a little derpy today. I forgot that the Ingame Text is from the Ingame Info XML mod. Sorry! :smile:
