### ISSUE TITLE
[Bug/Crash] Game crash with CMM version 1.7

### ISSUE THREAD

**Issue by SnowShock35** [lumien231/Custom-Main-Menu#56]
Hi lumien,

Having a crash with CMM...

Minecraft 1.7.10
Forge 10.13.4.1448
CMM Version 1.7
JSON File: http://paste.ee/p/6bA5d
Crash Report: http://paste.ee/p/ArRfy

**Comment by lumien231** [comment]
Whoops, 1.7 makes every gui without a splash text crash. Will upload the fixed version today.

**Comment by SnowShock35** [comment]
Thx @lumien231
