### ISSUE TITLE
button not showing on menu

### ISSUE THREAD

**Issue by wackoamd1** [lumien231/Custom-Main-Menu#58]
i have this weird issue where a wrapped button isnt showing on the main menu
here is my json: 

{
    "images":
    {
        "title":
        {
            "image" : "custommainmenu:textures/gui/minecraft.png",
            "posX" : -137,
            "posY" : 30,
            "width" : 512,
            "height" : 512,
            "alignment" : "top_center"
        }
    },
    
    "buttons":
    {
        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX": -100,
            "posY": -24,
            "alignment": "center",
            "width": 98,
            "height": 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
        
        "multiplayer":
        {
            "text" : "menu.multiplayer",
            "posX": 2,
            "posY": -24,
            "alignment": "center",
            "width": 98,
            "height": 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
        
        "mods":
        {
            "text" : "Mods",
            "posX": -100,
            "posY": 0,
            "alignment": "center",
            "width": 200,
            "height": 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },
            
        "options":
        {
            "text" : "menu.options",
            "posX": -100,
            "posY": 24,
            "alignment": "center",
            "width": 98,
            "height": 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
        
        "quit":
        {
            "text" : "menu.quit",
            "posX": 2,
            "posY": 24,
            "alignment": "center",
            "width": 98,
            "height": 20,
            "action" : 
            {
                "type" : "quit"
            }
        },
        
        "language":
        {
            "text" : "",
            "posX": 2,
            "posY": 48,
            "alignment": "center",
            "width": 20,
            "height": 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        
        "ServerSync": {
            "text": "Serversync",
            "posX": -100,
            "posY": 48,
            "alignment": "center",
            "width": 98,
            "height": 20,
            "tooltip": "Sync your mods with the server",
            "wrappedButton": 6001
			}
		},
    
    "texts":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right"
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -50,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center",
            "file" : "texts/splashes.txt"
        },
        
        "panorama":
        {
            "images" : "minecraft:textures/gui/title/background/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}

the server sync button isnt showing up and i checked the button id which is correct.
no error , nothing weird in the log it just isnt there

ccm 1.7.1 mc 1.7.10

**Comment by lumien231** [comment]
https://github.com/superzanti/ServerSync/issues/27
