### ISSUE TITLE
Missing texture

### ISSUE THREAD

**Issue by JasonMcRay** [lumien231/Custom-Main-Menu#60]
Ok. First of all there is most likely something I am doing wrong, but i spent 2hrs just trying to figure this out but no luck.

I have both CMM and Resource Loader installed.
My folder structure for resource is:
minecraft/resources/test/textures/menubg.png

In mainmenu.json file I haver this line:
"other":{  
"background":
        {
            "image" : "test:textures/menubg.png"
        }
}

In menu I just have Missing texture background (purple/black square).

In the console I am no getting any error about missing texture

**Comment by JasonMcRay** [comment]
It seems like the reload button is not working if I change the images names.. I restarted the client and it now works just fine.

**Comment by lumien231** [comment]
The reload button is not able to detect NEW resources,
