### ISSUE TITLE
Completely White Screen while using certain json files

### ISSUE THREAD

**Issue by shaharcoolmen** [lumien231/Custom-Main-Menu#61]
whenever i try to change the menu and i want to relaunch minecraft its putting a white screen
and no thing wierd in the config happens

**Comment by shaharcoolmen** [comment]
the code im trying to use is:
{
    "images":
    {
        
    },
    
    "buttons":
    {
        "play":
        {
            "text" : "Play",
            "posX" : -100,
            "posY" : 48,
			
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
            
        "options":
        {
            "text" : "menu.options",
            "posX" : -100,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
        
        "quit":
        {
            "text" : "menu.quit",
            "posX" : 2,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "quit"
            }
        },
        
        "language":
        {
            "text" : "",
            "posX" : -124,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        
        "refresh":
        {
            "text" : "",
            "posX" : -154,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "texts":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right"
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_left"
        },

	"shaharcoolmen":
        {
            "text" : "Made By shaharcoolmen(this client is unofficial!)",
            "posX" : 2,
            "posY" : -20,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center",
            "file" : "texts/splashes.txt"
        },
        
        "background":
        {
            "image" : "wynncraft:textures/background.png"
        }
    }
}
and i have resource manager installed

**Comment by shaharcoolmen** [comment]
the problem is with my coding i think but every texture is in place and when i do refresh everything is fine but relaunching white screen

**Comment by shaharcoolmen** [comment]
it seems to be a problem with my background

**Comment by shaharcoolmen** [comment]
ok so what i did in the end is i made it panorama like default and them made an image to override
the panorama, there is a problem with changing any part of the "other" section of the code


this is the code i used at the end

{
    "images":
    {
        "BG":
        {
            "image" : "wynncraft:textures/background.png",
            "posX" : -300,
            "posY" : -175,
            "width" : 600,
            "height" : 350,
            "alignment" : "center"
        }
    },
    
    "buttons":
    {
        "play":
        {
            "text" : "§2Play",
            "posX" : -100,
            "posY" : 48,	
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "connectToServer",
                "ip" : "play.wynncraft.com"
            }
        },
            
        "options":
        {
            "text" : "menu.options",
            "posX" : -100,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
        
        "quit":
        {
            "text" : "menu.quit",
            "posX" : 2,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "quit"
            }
        },
        
        "language":
        {
            "text" : "",
            "posX" : -124,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        
        "refresh":
        {
            "text" : "",
            "posX" : -154,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "texts":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right"
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_left"
        },

	"shaharcoolmen":
        {
            "text" : "Made By shaharcoolmen(this client is unofficial!)",
            "posX" : 2,
            "posY" : -20,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center",
            "file" : "texts/splashes.txt"
        },
        
        "panorama":
        {
            "images" : "minecraft:textures/gui/title/background/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}

**Comment by shaharcoolmen** [comment]
@lumien231 please fix that...

**Comment by lumien231** [comment]
Well if i use the configs you posted i don't get a white screen, i obviously get black purple checkerboard because i don't have the texture but no white screen.
