### ISSUE TITLE
[Suggestion] Image slideshow

### ISSUE THREAD

**Issue by JasonMcRay** [lumien231/Custom-Main-Menu#62]
I know its possible to use slideshow for background. But I would really welcome if the slideshow function would be possible for diferent images as well..

What exactly I would like to be able to do is following:
1) Have one single image as backround which will never change.
2) Have one picture on the left and one picture on the right
3) These pictures i would like to change.

I know i could just use background with slideshow, and have those images "within" the backround. But I  would like to have those pictures to be randomized as well.

It is supposed to be something like pictures from players builds as a postcard.

here is just an example:
http://i.imgur.com/hgKlzRh.jpg

**Comment by lumien231** [comment]
So slideshows for images & maybe also rotation parameters?

**Comment by JasonMcRay** [comment]
Yup, thats exactly it.

If I also may, i see that for background slideshow the images are put in an arrray, would it be possible to use similiar way as it is with panorama?

So instead of having
"images" : 
[
"test:test/img_01.png",
"test:test/img_02.png
]

to have

"images" : "test:test/img_%c.png"

?

**Comment by lumien231** [comment]
Okay so i have them done, there just won't be the sync property that the "background" slideshow has.
