### ISSUE TITLE
Image Textures

### ISSUE THREAD

**Issue by tak7871** [lumien231/Custom-Main-Menu#65]
Whenever i use a .png or .gif it just shows up as the purple and black unrendered textures. any idea what is wrong

**Comment by lumien231** [comment]
Do you have Resource Loader installed? And do you get any errors in console?

**Comment by tak7871** [comment]
i downloaded resource loader and now minecraft wont launch.

**Comment by lumien231** [comment]
Did you download the proper version for your mc version?

**Comment by tak7871** [comment]
Yes 1.7.10

**Comment by lumien231** [comment]
Could you post your log and a picture of your folder structure? (Where the image is)

**Comment by SkullHunter** [comment]
That happens for me to even when i download a preconfigured config/images it crashes

**Comment by SkullHunter** [comment]
i mean get purple screen
