### ISSUE TITLE
Slow "image download"

### ISSUE THREAD

**Issue by JasonMcRay** [lumien231/Custom-Main-Menu#67]
I have an image hosted on the web, but its taking slightly longer to appear in the menu (the file is only 330kB and it takes few seconds to appear. Would it be possible to for example let the CMM download the images on startup instead of when its needed to speed this up?

**Comment by lumien231** [comment]
Huh, they should start loading once the config is read which happens in preInit.

**Comment by JasonMcRay** [comment]
I have that image inside other custom made GUI if it makes any change

**Comment by JasonMcRay** [comment]
Hmm.. just tried it again, and now it works fine... Dont know what happend, maybe my net connection was slightly broken... Sorry :)
