### ISSUE TITLE
Color code problems

### ISSUE THREAD

**Issue by ZombieHDGaming** [lumien231/Custom-Main-Menu#7]
Hey there, love your mod and I plan on using it in my modpack, but there is a problem with the color code support in the JSON code. Every time I put in a section sign (§), there is always a weird symbol that appears. The picture below shows my current setup b4 I figured out the color option in the code. (P.S. look in the lower left corner to see bug)
![custommenumod bug](https://cloud.githubusercontent.com/assets/10361287/5591238/37e6f7cc-911e-11e4-9a02-9712917dbf00.PNG)
As much as I like the mod itself, which is absolutely great, but with the color code being broken is really a pain in the (you know what this supposed to be), and I really hope you can release a patch fix for 1.7.10 so I can finish this modpack and submit it.

Cheers,
ZombieHDGaming

**Comment by ZombieHDGaming** [comment]
And also, the ColorHover feature in the JSON code is unusable as every time I try to use that code, it gives an error saying that it's not compatible with the mod and it is a real pain as I just want normal colors for my text when I hover over them.

**Comment by lumien231** [comment]
First of all, don't report stuff as if you KNOW that it is broken. Everything you describe works perfectly fine for me

If you get that symbol you might wanna change the Encoding you are saving the file in, i sometimes had problems with that.

For the hoverTextColor property of texts, it sounds like you just messed up the json. If you are sure that you did it correct post the error log please.

**Comment by ZombieHDGaming** [comment]
How might you suggest changing the encoding for not getting the symbol? I'm sry but I'm a noob with JSON as I'm using an online editor. And I'm using MultiMC for my modpack and it doesn't give me specifics with the hoverTextColor. If you can help, I'll gladly post my config for you to look at, and possibly make corrections or suggestions.

**Comment by lumien231** [comment]
I don't know how to change the encoding in your online editor :P, can't you open up the config file in notepad++ or something? 

And MultiMC has the console window right? Does it not print anything there? And if not where are you getting the "it's not compatible with the mod" from?

Yes please post your config file.

**Comment by ZombieHDGaming** [comment]
I tried to open the JSON config with Notepad but my computer denied it and wouldn't allow me to, so that was my next option.

HoverColor Problem:
{
  "images": {
    "title": {
      "image": "custommainmenu:textures/gui/minecraft.png",
      "posX": -137,
      "posY": 30,
      "width": 512,
      "height": 512,
      "alignment": "top_center"
    }
  },
  "buttons": {
    "singleplayer": {
      "text": "menu.singleplayer",
      "posX": -225,
      "posY": 48,
      "width": 200,
      "height": 20
    },
    "multiplayer": {
      "text": "menu.multiplayer",
      "posX": 24,
      "posY": 48,
      "width": 200,
      "height": 20
    },
    "mods": {
      "text": "fml.menu.mods",
      "posX": -100,
      "posY": 72,
      "width": 200,
      "height": 20
    },
    "options": {
      "text": "menu.options",
      "posX": -100,
      "posY": 96,
      "width": 98,
      "height": 20
    },
    "quit": {
      "text": "menu.quit",
      "posX": 2,
      "posY": 96,
      "width": 98,
      "height": 20
    },
    "language": {
      "text": "",
      "posX": -11,
      "posY": 48,
      "width": 20,
      "height": 20
    },
    "refresh": {
      "text": "",
      "posX": -154,
      "posY": 132,
      "width": 20,
      "height": 20
    }
  },
  "texts": {
    "Developer Info": {
      "text": "Developed by ZombieHDGaming",
      "posX": 2,
      "posY": -20,
      "color": 65280,
      "hoverColor": 65280
      "alignment": "bottom_left"
    },
    "Mechanical OverDrive": {
      "text": "Mechanical OverDrive",
      "posX": 2,
      "posY": -30,
      "color": 16753920,
      "hoverColor": 16753920
      "alignment": "bottom_left"
    }
  },
  "other": {
    "splash-text": {
      "posX": 90,
      "posY": 70,
      "color": -256,
      "alignment": "top_center"
    },
    "panorama": {
      "images": "minecraft:textures/gui/title/background/panorama_%c.png",
      "blur": true,
      "gradient": true
    }
  }
}

I believe I already figured this one out but you can still check and
Color Code Problem:
{
  "images": {
    "title": {
      "image": "custommainmenu:textures/gui/minecraft.png",
      "posX": -137,
      "posY": 30,
      "width": 512,
      "height": 512,
      "alignment": "top_center"
    }
  },
  "buttons": {
    "singleplayer": {
      "text": "menu.singleplayer",
      "posX": -225,
      "posY": 48,
      "width": 200,
      "height": 20
    },
    "multiplayer": {
      "text": "menu.multiplayer",
      "posX": 24,
      "posY": 48,
      "width": 200,
      "height": 20
    },
    "mods": {
      "text": "fml.menu.mods",
      "posX": -100,
      "posY": 72,
      "width": 200,
      "height": 20
    },
    "options": {
      "text": "menu.options",
      "posX": -100,
      "posY": 96,
      "width": 98,
      "height": 20
    },
    "quit": {
      "text": "menu.quit",
      "posX": 2,
      "posY": 96,
      "width": 98,
      "height": 20
    },
    "language": {
      "text": "",
      "posX": -11,
      "posY": 48,
      "width": 20,
      "height": 20
    },
    "refresh": {
      "text": "",
      "posX": -154,
      "posY": 132,
      "width": 20,
      "height": 20
    }
  },
  "texts": {
    "Developer Info": {
      "text": "§bDeveloped by §aZombieHDGaming",
      "posX": 2,
      "posY": -20,
      "color": -1,
      "hoverColor": -1,
      "alignment": "bottom_left"
    },
    "Mechanical OverDrive": {
      "text": "§6Mechanical OverDrive",
      "posX": 2,
      "posY": -30,
      "color": -1,
      "hoverColor": -1,
      "alignment": "bottom_left"
    }
  },
  "other": {
    "splash-text": {
      "posX": 90,
      "posY": 70,
      "color": -256,
      "alignment": "top_center"
    },
    "panorama": {
      "images": "minecraft:textures/gui/title/background/panorama_%c.png",
      "blur": true,
      "gradient": true
    }
  }
}

these are 2 different JSON configs but that was because I had to update the mod but anyway, the § problem is honestly the only huge problem I have

**Comment by ZombieHDGaming** [comment]
And MultiMC does have the console window but the launcher just spits back, "[20:23:52] [Client thread/ERROR] [CustomMainMenu]: Error while loading new config file, trying to keep the old one loaded." and this happens when the code is incorrect most of the time.

**Comment by lumien231** [comment]
So yeah, for the first config file you were missing a comma behind the hoverColor settings.
And like i said, it works fine when i save that file in ASCII instead of UTF8. And i don't see why you shouldn't be able to open the file.

**Comment by ZombieHDGaming** [comment]
Well, yea my computer finally worked after like 4 days and it opened the config. And do mind explaining what the hell you were talking bout the second to last sentence? Again, noob with JSON.

**Comment by lumien231** [comment]
It has nothing to do with json, download notepad++ and open the json file with that. On the top you should see a Encoding section, select ASCII there. The weird symbols should then become visible, delete them and save the file and it should work.

**Comment by ZombieHDGaming** [comment]
Ok, never mind. I got the fix to the mod by testing before you sent your msg, but thanks for your help anyway Lumien. I'll make sure you are on the alpha testing list for the modpack once I get it on the ATLauncher, and you will have contributor's rights to the modpack. So just shoot me a msg if you need the name for the pack.

**Comment by lumien231** [comment]
kk :)

**Comment by ZombieHDGaming** [comment]
Wait! I have a question bout the mod. Is there any way to display how many mods are active in FML using a text? I'm just asking as I saw Bacon_Donut use this mod for his Sky Factory 2 modpack and he had a number of active mods in the pack under the pack name

**Comment by lumien231** [comment]
I mean you can add custom texts so you can just add the number of mods in the pack.

You can also move the default fml text if you want.

**Comment by ZombieHDGaming** [comment]
Yeah, but the default FML text is big and it's just not a good place holder if you get my drift

**Comment by lumien231** [comment]
I will at place holder strings at some point that will allow you to use certain values like active mods etc. in your custom texts.

**Comment by ZombieHDGaming** [comment]
That sounds great, I can't wait to see that added. I will definitely use this in my other modpacks that I'm making.
