### ISSUE TITLE
Placeholders in file uris and web urls

### ISSUE THREAD

**Issue by tenten8401** [lumien231/Custom-Main-Menu#73]
Title says it basicially, Would be nice if we could use placeholders in URIs

**Comment by tenten8401** [comment]
Couldnt help but notice you released 1.9.2 but this is milestone 2.0... was this fix included in 1.9.2 or what...

**Comment by lumien231** [comment]
No, i just had to quickly fix a crashing bug so i made a 1.9.2. 2.0 Will be the next "feature" version which will also contain this.

**Comment by tenten8401** [comment]
I have 1.9.1 in my modpack (IndustrialBox) and I don't see any issues.
Still waiting for 2.0 so I can make a nicer menu design. Also is there a
way you can also add a way to truely center align things, as in center
align text so you won't have to worry how long the text is to center it
properly

**Comment by lumien231** [comment]
Centered Text is a good idea. The crash was only occuring on certain system languages like turkish.

**Comment by tenten8401** [comment]
Okay. You should really get a build server going and open source the code
as well. I would be happy to host you a build server if you want

**Comment by lumien231** [comment]
Ehhh, why again?

**Comment by tenten8401** [comment]
Open sourcing a project gets a lot more contributors and you don't have to put as much effort into bug fixes.

**Comment by lumien231** [comment]
Yeah but it isn't much effort to begin with :P. It's a pretty small mod.

**Comment by tenten8401** [comment]
When is 2.0 coming out anyways?

**Comment by tenten8401** [comment]
Going to assume 2.0 is an imaginary goal.

**Comment by lumien231** [comment]
It isn't.
