### ISSUE TITLE
Play Custom Title Music

### ISSUE THREAD

**Issue by Alaberti** [lumien231/Custom-Main-Menu#74]
Is it possible to have an option to play custom music in the background?

**Comment by lumien231** [comment]
Yes, you can actually do that with vanilla resource packs (Which makes it possible with Resource Loader). 

This is a video on how to do it: https://youtu.be/Ixhq6bRbLZ4?t=2m11s

**Comment by Alaberti** [comment]
As the kids do, "<3" though it looks more like a fallen ice cream cone than a heart the sentiment should count for something right?
