### ISSUE TITLE
Menu buttons not clickable

### ISSUE THREAD

**Issue by emjnkr** [lumien231/Custom-Main-Menu#77]
After changing the mainmenu.json the menu buttons became unclickable. The openlink buttons work however. 

My mainmenu.json is as followed: http://hastebin.com/raw/awekisenuv

Using minecraft 1.7.10, forge 1456

**Comment by lumien231** [comment]
Yeah you removed their action :P. That's why they don't work. Look at the vanilla json file to see how to make them work again.

**Comment by emjnkr** [comment]
Ah, I figured something like that was wrong. All the examples over [here](http://www.curse.com/mc-mods/minecraft/226406-custom-main-menu#t1:description) don't have an action, I figured that's just how it works.

Would you mind posting the vanilla json file?

**Comment by lumien231** [comment]
If you don't have a mainmenu.json it is going to automatically create the vanilla one :).
