### ISSUE TITLE
Help me, connectToServer Bug

### ISSUE THREAD

**Issue by Zenden300** [lumien231/Custom-Main-Menu#78]
Hello, having spent one hour trying to solve my problem, I post on this forum.
I want to clarify that I'm French and if I'm spelling mistakes excuse me. ( si il y a des Français ici, vous pouvez me répondre en français).
My problem is that trying to make a connection to a server button, my crash games.
I am inspired by a model on the forum, here: https://github.com/lumien231/Custom-Main-Menu/issues/64

Here are the logs of the crash: http://pastebin.com/04LDv5DA

Logs Custom Main Menu: http://pastebin.com/Q2KmrADc

**Comment by lumien231** [comment]
You should run your menus through online json checkers before reporting problems :). Your json is invalid.
