### ISSUE TITLE
Minecraft Color Coded Text doesn't hide code

### ISSUE THREAD

**Issue by JimmyMac3** [lumien231/Custom-Main-Menu#8]
When you add text with minecraft § color codes it changes the text color but also displays the § symbol as part of the text.

**Comment by lumien231** [comment]
It doesn't for me :P. Screenshot please?

**Comment by JimmyMac3** [comment]
http://gyazo.com/84cb220bf64aa6c13f09202b37b27529  <-- Screen Shot of the problem on Gyazo. I took the codes out of the current version that we sent to FTB but it would be nice if we could get this to work.

In case you want to check out the pack and the other mods in it (maybe something is conflicting) -

Run Dig Hide version 1.1 beta on FTB launcher 3rd Party packs. Pack Code is ptnoobcrew (this newest version should be available on FTB in the next few hours)
Latest info on the pack and all the mods in it is at http://noobmc.com/index.php/run-dig-hide-modpack

**Comment by JimmyMac3** [comment]
Thanks. That fixed it. Works great now! :)
