### ISSUE TITLE
Config links broken

### ISSUE THREAD

**Issue by ajthemacboy** [lumien231/Custom-Main-Menu#83]
Hi, I'm interested in obtaining the config for example number 10 on the website: https://i.imgur.com/TlqdZ11.jpg

Many of the config links on Curse are broken, however. Can these be fixed?

**Comment by lumien231** [comment]
How is it broken? I can access it just fine.

**Comment by ajthemacboy** [comment]
When I click them, it takes me to the Pastebin homepage. Maybe it's just on my end?

Sorry if it is!

**Comment by lumien231** [comment]
Does it work if you just directly go to the link?

http://pastebin.com/qJHC1mne

**Comment by ajthemacboy** [comment]
Yep. I'm pretty sure this is on my end, closing this. Sorry!
