### ISSUE TITLE
Inconsistent gui passed in GuiScreenEvent

### ISSUE THREAD

**Issue by Filipsi** [lumien231/Custom-Main-Menu#86]
Minecraft verson: 1.7.10
Minecraft Forge verson: 10.13.4.1614
Mod verson: 1.9.2

While on MainMenu screen, parameter gui of event
- GuiScreenEvent.DrawScreenEvent.Post returns lumien.custommainmenu.gui.GuiCustom
- GuiScreenEvent.InitGuiEvent.Post returns lumien.custommainmenu.gui.GuiFakeMain

These events should return the same thing, like vanilla.

**Comment by lumien231** [comment]
Why, what issues does this cause? The reason i return a "fake" main menu in InitGuiEvent is so that mods still add their respective buttons to the main menu.
