### ISSUE TITLE
Adding server-resourcepacks to connect to server in cmm mod

### ISSUE THREAD

**Issue by vrackfall** [lumien231/Custom-Main-Menu#88]
Hi Lumien, could you add an feature to "enable/disable the server resourcepack" to the "connect to server" action of cmm mod you made ?
Thanks

**Comment by lumien231** [comment]
#84

**Comment by vrackfall** [comment]
So you already planned this or it's already in the mod ?

**Comment by lumien231** [comment]
Already planned :)

**Comment by vrackfall** [comment]
Ok thanks

**Comment by lumien231** [comment]
Just fyi. Won't add this since it's not possible in vanilla to force a server resource pack on users.

**Comment by vrackfall** [comment]
Ok, it's okay
