### ISSUE TITLE
Resource-packs button.

### ISSUE THREAD

**Issue by GizmoCodes** [lumien231/Custom-Main-Menu#89]
So, on my title screen I want to add a Resource Packs button, but no-matter what I try, my button never goes to the Resource Packs screen, leading me to think its not in the mod. What I mean is I could add an action like so:
```
"action" : 
    {
        "type" : "openGui",
         "gui" : "resource-packs"
    }
```
And that would go to the Resource Packs page.

Is this already in the mod or could it be added?

**Comment by GizmoCodes** [comment]
Also, what about opening the Controls menu?

**Comment by lumien231** [comment]
There is a link to a list on the curseforge pages :)

http://pastebin.com/dJzLgnSL
