### ISSUE TITLE
Crashes on 2nd init phase

### ISSUE THREAD

**Issue by fabbe50** [lumien231/Custom-Main-Menu#90]
Crashes when loading up the mod, not really sure what's happening.
Here's the crash stacktrace atleast: http://pastebin.com/ii1HhmBA

**Comment by lumien231** [comment]
Could you post your json file please? Did you perhaps remove whole categorys from it? Even if you don't have for example texts in your json file you still need to keep the category.

**Comment by fabbe50** [comment]
Couldn't upload the json file directly so here it is on pastebin: http://pastebin.com/4WGQAL5S

**Comment by lumien231** [comment]
It's "texts" not "text".

**Comment by fabbe50** [comment]
Thank you!
