### ISSUE TITLE
§ Color Codes not working correctly

### ISSUE THREAD

**Issue by Yanniclord** [lumien231/Custom-Main-Menu#93]
So, when i try adding multiple color codes (or just one) to a text in the main menu, i end up getting an À infront of that text. Here, look:

![unbenannt](https://cloud.githubusercontent.com/assets/5807595/13272733/82062d30-da9e-11e5-9c67-0fc5037fc9ff.png)

The UI is still in work, but it does mainly function.

**Comment by Yanniclord** [comment]
So the config derped, and i ended up getting a lot of other stuff in it, but it actually somewhat helped me. It ended up replacing the color code symbol with ง, and if i use that, it actually works without the weird A.

**Comment by lumien231** [comment]
Generally if you save your config file in ASCII encoding it will fix itself as well.
