### ISSUE TITLE
Animated PNGs only display first frame

### ISSUE THREAD

**Issue by Teteros** [lumien231/Custom-Main-Menu#96]
Is APNG support in any of 1.7.10 CMM releases?
With `CustomMainMenu-MC1.7.10-1.9.2.jar` animated PNGs are not played as if they're animated in the custom main menu, they seem to behave like normal (single-framed) PNGs.

The background APNG file is using the .apng extension as [suggested on curse](http://minecraft.curseforge.com/projects/custom-main-menu?comment=467):
```
"background":
{
	"image" : "mainmenu:textures/bg.apng"
}
```
>the library i use to read apngs has issues with certain apngs. If you want to use one that doesn't work running it through some converters / apng creators often fixes it.

Could you provide an example of a working APNG background?

I've tried creating some APNG files by converting GIFs with [gif2apng](http://gif2apng.sourceforge.net/) None of zlib,7z and zopfli compression methods worked and neither images/videos via ffmpeg (has apng encoder since sep 2015 to my surprise).

**Comment by lumien231** [comment]
There isn't at the moment, will probably make a last 1.7.10 version before updating 1.9 that will include it.

**Comment by lumien231** [comment]
Fyi. i will not make another 1.7.10 update.Sorry.
