### ISSUE TITLE
Custom Sound?

### ISSUE THREAD

**Issue by SirWyld** [lumien231/Custom-Main-Menu#97]
Greeting good sir

I was wondering if it would be possible to play a custom .ogg sound file within the main menu? Because that, would be freaking amazing.

-- Wyld

**Comment by lumien231** [comment]
You can replace the vanilla menu music (Which i assume is what you are talking about) using Resource Loader.

**Comment by SirWyld** [comment]
I would *prefer* to not replace the vanilla tracks .. more a case of having an additional .ogg file that could be used.

**Comment by SirWyld** [comment]
Another thought, using a mod like Custom Things allows us to create our own records. Perhaps, the ability to play one of them? Just trying to think outside the box.

**Comment by lumien231** [comment]
This setup adds dragon.ogg as a possible music to play in the menu:
https://i.imgur.com/K3hNJxP.png

**Comment by lumien231** [comment]
Also since Resource Loader does everything a resource pack does you can just google how to do stuff with a resource pack.

**Comment by SirWyld** [comment]
Awesome, thanks mate. Will start tinkering :+1:
